/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BusinessReportFormat;
import org.openapitools.client.model.BusinessReportScheduleLastBusinessReport;
import org.openapitools.client.model.CreateBusinessReportScheduleRequestContentRange;
import org.openapitools.client.model.UpdateBusinessReportScheduleRequestRecurrence;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BusinessReportSchedule
 */
public class BusinessReportScheduleTest {
    private final BusinessReportSchedule model = new BusinessReportSchedule();

    /**
     * Model tests for BusinessReportSchedule
     */
    @Test
    public void testBusinessReportSchedule() {
        // TODO: test BusinessReportSchedule
    }

    /**
     * Test the property 'scheduleArn'
     */
    @Test
    public void scheduleArnTest() {
        // TODO: test scheduleArn
    }

    /**
     * Test the property 'scheduleName'
     */
    @Test
    public void scheduleNameTest() {
        // TODO: test scheduleName
    }

    /**
     * Test the property 's3BucketName'
     */
    @Test
    public void s3BucketNameTest() {
        // TODO: test s3BucketName
    }

    /**
     * Test the property 's3KeyPrefix'
     */
    @Test
    public void s3KeyPrefixTest() {
        // TODO: test s3KeyPrefix
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'contentRange'
     */
    @Test
    public void contentRangeTest() {
        // TODO: test contentRange
    }

    /**
     * Test the property 'recurrence'
     */
    @Test
    public void recurrenceTest() {
        // TODO: test recurrence
    }

    /**
     * Test the property 'lastBusinessReport'
     */
    @Test
    public void lastBusinessReportTest() {
        // TODO: test lastBusinessReport
    }

}
