/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.BusinessReportFailureCode;
import org.openapitools.client.model.BusinessReportS3Location;
import org.openapitools.client.model.BusinessReportStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BusinessReportScheduleLastBusinessReport
 */
public class BusinessReportScheduleLastBusinessReportTest {
    private final BusinessReportScheduleLastBusinessReport model = new BusinessReportScheduleLastBusinessReport();

    /**
     * Model tests for BusinessReportScheduleLastBusinessReport
     */
    @Test
    public void testBusinessReportScheduleLastBusinessReport() {
        // TODO: test BusinessReportScheduleLastBusinessReport
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'failureCode'
     */
    @Test
    public void failureCodeTest() {
        // TODO: test failureCode
    }

    /**
     * Test the property 's3Location'
     */
    @Test
    public void s3LocationTest() {
        // TODO: test s3Location
    }

    /**
     * Test the property 'deliveryTime'
     */
    @Test
    public void deliveryTimeTest() {
        // TODO: test deliveryTime
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    public void downloadUrlTest() {
        // TODO: test downloadUrl
    }

}
