/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ConferenceProviderType;
import org.openapitools.client.model.CreateConferenceProviderRequestIPDialIn;
import org.openapitools.client.model.CreateConferenceProviderRequestMeetingSetting;
import org.openapitools.client.model.CreateConferenceProviderRequestPSTNDialIn;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateConferenceProviderRequest
 */
public class CreateConferenceProviderRequestTest {
    private final CreateConferenceProviderRequest model = new CreateConferenceProviderRequest();

    /**
     * Model tests for CreateConferenceProviderRequest
     */
    @Test
    public void testCreateConferenceProviderRequest() {
        // TODO: test CreateConferenceProviderRequest
    }

    /**
     * Test the property 'conferenceProviderName'
     */
    @Test
    public void conferenceProviderNameTest() {
        // TODO: test conferenceProviderName
    }

    /**
     * Test the property 'conferenceProviderType'
     */
    @Test
    public void conferenceProviderTypeTest() {
        // TODO: test conferenceProviderType
    }

    /**
     * Test the property 'ipDialIn'
     */
    @Test
    public void ipDialInTest() {
        // TODO: test ipDialIn
    }

    /**
     * Test the property 'psTNDialIn'
     */
    @Test
    public void psTNDialInTest() {
        // TODO: test psTNDialIn
    }

    /**
     * Test the property 'meetingSetting'
     */
    @Test
    public void meetingSettingTest() {
        // TODO: test meetingSetting
    }

    /**
     * Test the property 'clientRequestToken'
     */
    @Test
    public void clientRequestTokenTest() {
        // TODO: test clientRequestToken
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
