/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DeviceStatusDetailCode;
import org.openapitools.client.model.Feature;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeviceStatusDetail
 */
public class DeviceStatusDetailTest {
    private final DeviceStatusDetail model = new DeviceStatusDetail();

    /**
     * Model tests for DeviceStatusDetail
     */
    @Test
    public void testDeviceStatusDetail() {
        // TODO: test DeviceStatusDetail
    }

    /**
     * Test the property 'feature'
     */
    @Test
    public void featureTest() {
        // TODO: test feature
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

}
