/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.DeviceDeviceStatusInfo;
import org.openapitools.client.model.DeviceStatus;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeviceData
 */
public class DeviceDataTest {
    private final DeviceData model = new DeviceData();

    /**
     * Model tests for DeviceData
     */
    @Test
    public void testDeviceData() {
        // TODO: test DeviceData
    }

    /**
     * Test the property 'deviceArn'
     */
    @Test
    public void deviceArnTest() {
        // TODO: test deviceArn
    }

    /**
     * Test the property 'deviceSerialNumber'
     */
    @Test
    public void deviceSerialNumberTest() {
        // TODO: test deviceSerialNumber
    }

    /**
     * Test the property 'deviceType'
     */
    @Test
    public void deviceTypeTest() {
        // TODO: test deviceType
    }

    /**
     * Test the property 'deviceName'
     */
    @Test
    public void deviceNameTest() {
        // TODO: test deviceName
    }

    /**
     * Test the property 'softwareVersion'
     */
    @Test
    public void softwareVersionTest() {
        // TODO: test softwareVersion
    }

    /**
     * Test the property 'macAddress'
     */
    @Test
    public void macAddressTest() {
        // TODO: test macAddress
    }

    /**
     * Test the property 'deviceStatus'
     */
    @Test
    public void deviceStatusTest() {
        // TODO: test deviceStatus
    }

    /**
     * Test the property 'networkProfileArn'
     */
    @Test
    public void networkProfileArnTest() {
        // TODO: test networkProfileArn
    }

    /**
     * Test the property 'networkProfileName'
     */
    @Test
    public void networkProfileNameTest() {
        // TODO: test networkProfileName
    }

    /**
     * Test the property 'roomArn'
     */
    @Test
    public void roomArnTest() {
        // TODO: test roomArn
    }

    /**
     * Test the property 'roomName'
     */
    @Test
    public void roomNameTest() {
        // TODO: test roomName
    }

    /**
     * Test the property 'deviceStatusInfo'
     */
    @Test
    public void deviceStatusInfoTest() {
        // TODO: test deviceStatusInfo
    }

    /**
     * Test the property 'createdTime'
     */
    @Test
    public void createdTimeTest() {
        // TODO: test createdTime
    }

}
