/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetGatewayRequest
 */
public class GetGatewayRequestTest {
    private final GetGatewayRequest model = new GetGatewayRequest();

    /**
     * Model tests for GetGatewayRequest
     */
    @Test
    public void testGetGatewayRequest() {
        // TODO: test GetGatewayRequest
    }

    /**
     * Test the property 'gatewayArn'
     */
    @Test
    public void gatewayArnTest() {
        // TODO: test gatewayArn
    }

}
