/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSkillGroupResponseSkillGroup
 */
public class GetSkillGroupResponseSkillGroupTest {
    private final GetSkillGroupResponseSkillGroup model = new GetSkillGroupResponseSkillGroup();

    /**
     * Model tests for GetSkillGroupResponseSkillGroup
     */
    @Test
    public void testGetSkillGroupResponseSkillGroup() {
        // TODO: test GetSkillGroupResponseSkillGroup
    }

    /**
     * Test the property 'skillGroupArn'
     */
    @Test
    public void skillGroupArnTest() {
        // TODO: test skillGroupArn
    }

    /**
     * Test the property 'skillGroupName'
     */
    @Test
    public void skillGroupNameTest() {
        // TODO: test skillGroupName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
