/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListSmartHomeAppliancesRequest
 */
public class ListSmartHomeAppliancesRequestTest {
    private final ListSmartHomeAppliancesRequest model = new ListSmartHomeAppliancesRequest();

    /**
     * Model tests for ListSmartHomeAppliancesRequest
     */
    @Test
    public void testListSmartHomeAppliancesRequest() {
        // TODO: test ListSmartHomeAppliancesRequest
    }

    /**
     * Test the property 'roomArn'
     */
    @Test
    public void roomArnTest() {
        // TODO: test roomArn
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

}
