/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EnablementTypeFilter;
import org.openapitools.client.model.SkillTypeFilter;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListSkillsRequest
 */
public class ListSkillsRequestTest {
    private final ListSkillsRequest model = new ListSkillsRequest();

    /**
     * Model tests for ListSkillsRequest
     */
    @Test
    public void testListSkillsRequest() {
        // TODO: test ListSkillsRequest
    }

    /**
     * Test the property 'skillGroupArn'
     */
    @Test
    public void skillGroupArnTest() {
        // TODO: test skillGroupArn
    }

    /**
     * Test the property 'enablementType'
     */
    @Test
    public void enablementTypeTest() {
        // TODO: test enablementType
    }

    /**
     * Test the property 'skillType'
     */
    @Test
    public void skillTypeTest() {
        // TODO: test skillType
    }

    /**
     * Test the property 'nextToken'
     */
    @Test
    public void nextTokenTest() {
        // TODO: test nextToken
    }

    /**
     * Test the property 'maxResults'
     */
    @Test
    public void maxResultsTest() {
        // TODO: test maxResults
    }

}
