/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EndOfMeetingReminderType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MeetingRoomConfigurationEndOfMeetingReminder
 */
public class MeetingRoomConfigurationEndOfMeetingReminderTest {
    private final MeetingRoomConfigurationEndOfMeetingReminder model = new MeetingRoomConfigurationEndOfMeetingReminder();

    /**
     * Model tests for MeetingRoomConfigurationEndOfMeetingReminder
     */
    @Test
    public void testMeetingRoomConfigurationEndOfMeetingReminder() {
        // TODO: test MeetingRoomConfigurationEndOfMeetingReminder
    }

    /**
     * Test the property 'reminderAtMinutes'
     */
    @Test
    public void reminderAtMinutesTest() {
        // TODO: test reminderAtMinutes
    }

    /**
     * Test the property 'reminderType'
     */
    @Test
    public void reminderTypeTest() {
        // TODO: test reminderType
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

}
