/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.MeetingRoomConfigurationEndOfMeetingReminder;
import org.openapitools.client.model.MeetingRoomConfigurationInstantBooking;
import org.openapitools.client.model.MeetingRoomConfigurationRequireCheckIn;
import org.openapitools.client.model.ProactiveJoin;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProfileMeetingRoomConfiguration
 */
public class ProfileMeetingRoomConfigurationTest {
    private final ProfileMeetingRoomConfiguration model = new ProfileMeetingRoomConfiguration();

    /**
     * Model tests for ProfileMeetingRoomConfiguration
     */
    @Test
    public void testProfileMeetingRoomConfiguration() {
        // TODO: test ProfileMeetingRoomConfiguration
    }

    /**
     * Test the property 'roomUtilizationMetricsEnabled'
     */
    @Test
    public void roomUtilizationMetricsEnabledTest() {
        // TODO: test roomUtilizationMetricsEnabled
    }

    /**
     * Test the property 'endOfMeetingReminder'
     */
    @Test
    public void endOfMeetingReminderTest() {
        // TODO: test endOfMeetingReminder
    }

    /**
     * Test the property 'instantBooking'
     */
    @Test
    public void instantBookingTest() {
        // TODO: test instantBooking
    }

    /**
     * Test the property 'requireCheckIn'
     */
    @Test
    public void requireCheckInTest() {
        // TODO: test requireCheckIn
    }

    /**
     * Test the property 'proactiveJoin'
     */
    @Test
    public void proactiveJoinTest() {
        // TODO: test proactiveJoin
    }

}
