/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SendAnnouncementRequestContent;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendAnnouncementRequest
 */
public class SendAnnouncementRequestTest {
    private final SendAnnouncementRequest model = new SendAnnouncementRequest();

    /**
     * Model tests for SendAnnouncementRequest
     */
    @Test
    public void testSendAnnouncementRequest() {
        // TODO: test SendAnnouncementRequest
    }

    /**
     * Test the property 'roomFilters'
     */
    @Test
    public void roomFiltersTest() {
        // TODO: test roomFilters
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'timeToLiveInSeconds'
     */
    @Test
    public void timeToLiveInSecondsTest() {
        // TODO: test timeToLiveInSeconds
    }

    /**
     * Test the property 'clientRequestToken'
     */
    @Test
    public void clientRequestTokenTest() {
        // TODO: test clientRequestToken
    }

}
