/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateNetworkProfileRequest
 */
public class UpdateNetworkProfileRequestTest {
    private final UpdateNetworkProfileRequest model = new UpdateNetworkProfileRequest();

    /**
     * Model tests for UpdateNetworkProfileRequest
     */
    @Test
    public void testUpdateNetworkProfileRequest() {
        // TODO: test UpdateNetworkProfileRequest
    }

    /**
     * Test the property 'networkProfileArn'
     */
    @Test
    public void networkProfileArnTest() {
        // TODO: test networkProfileArn
    }

    /**
     * Test the property 'networkProfileName'
     */
    @Test
    public void networkProfileNameTest() {
        // TODO: test networkProfileName
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'currentPassword'
     */
    @Test
    public void currentPasswordTest() {
        // TODO: test currentPassword
    }

    /**
     * Test the property 'nextPassword'
     */
    @Test
    public void nextPasswordTest() {
        // TODO: test nextPassword
    }

    /**
     * Test the property 'certificateAuthorityArn'
     */
    @Test
    public void certificateAuthorityArnTest() {
        // TODO: test certificateAuthorityArn
    }

    /**
     * Test the property 'trustAnchors'
     */
    @Test
    public void trustAnchorsTest() {
        // TODO: test trustAnchors
    }

}
