package main

import (
	"github.com/alexa-for-business/mcp-server/config"
	"github.com/alexa-for-business/mcp-server/models"
	tools_x_amz_target_alexaforbusiness_updatebusinessreportschedule "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updatebusinessreportschedule"
	tools_x_amz_target_alexaforbusiness_updateaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updateaddressbook"
	tools_x_amz_target_alexaforbusiness_listconferenceproviders "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listconferenceproviders"
	tools_x_amz_target_alexaforbusiness_getgateway "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getgateway"
	tools_x_amz_target_alexaforbusiness_deleteroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteroom"
	tools_x_amz_target_alexaforbusiness_listdeviceevents "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listdeviceevents"
	tools_x_amz_target_alexaforbusiness_associatecontactwithaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associatecontactwithaddressbook"
	tools_x_amz_target_alexaforbusiness_getroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getroom"
	tools_x_amz_target_alexaforbusiness_updatedevice "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updatedevice"
	tools_x_amz_target_alexaforbusiness_getprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getprofile"
	tools_x_amz_target_alexaforbusiness_searchcontacts "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchcontacts"
	tools_x_amz_target_alexaforbusiness_searchnetworkprofiles "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchnetworkprofiles"
	tools_x_amz_target_alexaforbusiness_putinvitationconfiguration "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_putinvitationconfiguration"
	tools_x_amz_target_alexaforbusiness_listbusinessreportschedules "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listbusinessreportschedules"
	tools_x_amz_target_alexaforbusiness_listtags "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listtags"
	tools_x_amz_target_alexaforbusiness_searchaddressbooks "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchaddressbooks"
	tools_x_amz_target_alexaforbusiness_forgetsmarthomeappliances "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_forgetsmarthomeappliances"
	tools_x_amz_target_alexaforbusiness_rejectskill "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_rejectskill"
	tools_x_amz_target_alexaforbusiness_createaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createaddressbook"
	tools_x_amz_target_alexaforbusiness_disassociatecontactfromaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_disassociatecontactfromaddressbook"
	tools_x_amz_target_alexaforbusiness_getnetworkprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getnetworkprofile"
	tools_x_amz_target_alexaforbusiness_updategatewaygroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updategatewaygroup"
	tools_x_amz_target_alexaforbusiness_searchprofiles "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchprofiles"
	tools_x_amz_target_alexaforbusiness_getskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getskillgroup"
	tools_x_amz_target_alexaforbusiness_listskillsstoreskillsbycategory "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listskillsstoreskillsbycategory"
	tools_x_amz_target_alexaforbusiness_listsmarthomeappliances "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listsmarthomeappliances"
	tools_x_amz_target_alexaforbusiness_deletebusinessreportschedule "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletebusinessreportschedule"
	tools_x_amz_target_alexaforbusiness_listskills "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listskills"
	tools_x_amz_target_alexaforbusiness_putconferencepreference "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_putconferencepreference"
	tools_x_amz_target_alexaforbusiness_disassociateskillfromusers "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_disassociateskillfromusers"
	tools_x_amz_target_alexaforbusiness_associateskillwithskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associateskillwithskillgroup"
	tools_x_amz_target_alexaforbusiness_getcontact "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getcontact"
	tools_x_amz_target_alexaforbusiness_deleteprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteprofile"
	tools_x_amz_target_alexaforbusiness_getinvitationconfiguration "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getinvitationconfiguration"
	tools_x_amz_target_alexaforbusiness_disassociateskillfromskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_disassociateskillfromskillgroup"
	tools_x_amz_target_alexaforbusiness_deleteroomskillparameter "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteroomskillparameter"
	tools_x_amz_target_alexaforbusiness_updateconferenceprovider "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updateconferenceprovider"
	tools_x_amz_target_alexaforbusiness_createnetworkprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createnetworkprofile"
	tools_x_amz_target_alexaforbusiness_getdevice "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getdevice"
	tools_x_amz_target_alexaforbusiness_deleteconferenceprovider "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteconferenceprovider"
	tools_x_amz_target_alexaforbusiness_deletecontact "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletecontact"
	tools_x_amz_target_alexaforbusiness_putroomskillparameter "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_putroomskillparameter"
	tools_x_amz_target_alexaforbusiness_sendannouncement "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_sendannouncement"
	tools_x_amz_target_alexaforbusiness_updatenetworkprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updatenetworkprofile"
	tools_x_amz_target_alexaforbusiness_createconferenceprovider "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createconferenceprovider"
	tools_x_amz_target_alexaforbusiness_deletegatewaygroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletegatewaygroup"
	tools_x_amz_target_alexaforbusiness_searchusers "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchusers"
	tools_x_amz_target_alexaforbusiness_listgateways "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listgateways"
	tools_x_amz_target_alexaforbusiness_createprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createprofile"
	tools_x_amz_target_alexaforbusiness_listgatewaygroups "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listgatewaygroups"
	tools_x_amz_target_alexaforbusiness_createcontact "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createcontact"
	tools_x_amz_target_alexaforbusiness_deleteuser "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteuser"
	tools_x_amz_target_alexaforbusiness_createbusinessreportschedule "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createbusinessreportschedule"
	tools_x_amz_target_alexaforbusiness_tagresource "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_tagresource"
	tools_x_amz_target_alexaforbusiness_associateskillgroupwithroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associateskillgroupwithroom"
	tools_x_amz_target_alexaforbusiness_listskillsstorecategories "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_listskillsstorecategories"
	tools_x_amz_target_alexaforbusiness_startdevicesync "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_startdevicesync"
	tools_x_amz_target_alexaforbusiness_deletedeviceusagedata "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletedeviceusagedata"
	tools_x_amz_target_alexaforbusiness_getgatewaygroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getgatewaygroup"
	tools_x_amz_target_alexaforbusiness_putskillauthorization "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_putskillauthorization"
	tools_x_amz_target_alexaforbusiness_associatedevicewithnetworkprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associatedevicewithnetworkprofile"
	tools_x_amz_target_alexaforbusiness_creategatewaygroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_creategatewaygroup"
	tools_x_amz_target_alexaforbusiness_disassociatedevicefromroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_disassociatedevicefromroom"
	tools_x_amz_target_alexaforbusiness_revokeinvitation "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_revokeinvitation"
	tools_x_amz_target_alexaforbusiness_sendinvitation "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_sendinvitation"
	tools_x_amz_target_alexaforbusiness_searchdevices "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchdevices"
	tools_x_amz_target_alexaforbusiness_resolveroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_resolveroom"
	tools_x_amz_target_alexaforbusiness_searchskillgroups "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchskillgroups"
	tools_x_amz_target_alexaforbusiness_createuser "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createuser"
	tools_x_amz_target_alexaforbusiness_updateskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updateskillgroup"
	tools_x_amz_target_alexaforbusiness_getconferenceprovider "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getconferenceprovider"
	tools_x_amz_target_alexaforbusiness_getaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getaddressbook"
	tools_x_amz_target_alexaforbusiness_disassociateskillgroupfromroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_disassociateskillgroupfromroom"
	tools_x_amz_target_alexaforbusiness_updategateway "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updategateway"
	tools_x_amz_target_alexaforbusiness_untagresource "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_untagresource"
	tools_x_amz_target_alexaforbusiness_createroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createroom"
	tools_x_amz_target_alexaforbusiness_approveskill "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_approveskill"
	tools_x_amz_target_alexaforbusiness_updatecontact "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updatecontact"
	tools_x_amz_target_alexaforbusiness_registeravsdevice "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_registeravsdevice"
	tools_x_amz_target_alexaforbusiness_deleteaddressbook "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteaddressbook"
	tools_x_amz_target_alexaforbusiness_getroomskillparameter "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getroomskillparameter"
	tools_x_amz_target_alexaforbusiness_deleteskillauthorization "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteskillauthorization"
	tools_x_amz_target_alexaforbusiness_updateprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updateprofile"
	tools_x_amz_target_alexaforbusiness_associateskillwithusers "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associateskillwithusers"
	tools_x_amz_target_alexaforbusiness_getconferencepreference "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_getconferencepreference"
	tools_x_amz_target_alexaforbusiness_searchrooms "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_searchrooms"
	tools_x_amz_target_alexaforbusiness_deleteskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deleteskillgroup"
	tools_x_amz_target_alexaforbusiness_deletedevice "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletedevice"
	tools_x_amz_target_alexaforbusiness_createskillgroup "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_createskillgroup"
	tools_x_amz_target_alexaforbusiness_associatedevicewithroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_associatedevicewithroom"
	tools_x_amz_target_alexaforbusiness_deletenetworkprofile "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_deletenetworkprofile"
	tools_x_amz_target_alexaforbusiness_startsmarthomeappliancediscovery "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_startsmarthomeappliancediscovery"
	tools_x_amz_target_alexaforbusiness_updateroom "github.com/alexa-for-business/mcp-server/tools/x_amz_target_alexaforbusiness_updateroom"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_alexaforbusiness_updatebusinessreportschedule.CreateUpdatebusinessreportscheduleTool(cfg),
		tools_x_amz_target_alexaforbusiness_updateaddressbook.CreateUpdateaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_listconferenceproviders.CreateListconferenceprovidersTool(cfg),
		tools_x_amz_target_alexaforbusiness_getgateway.CreateGetgatewayTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteroom.CreateDeleteroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_listdeviceevents.CreateListdeviceeventsTool(cfg),
		tools_x_amz_target_alexaforbusiness_associatecontactwithaddressbook.CreateAssociatecontactwithaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_getroom.CreateGetroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_updatedevice.CreateUpdatedeviceTool(cfg),
		tools_x_amz_target_alexaforbusiness_getprofile.CreateGetprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchcontacts.CreateSearchcontactsTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchnetworkprofiles.CreateSearchnetworkprofilesTool(cfg),
		tools_x_amz_target_alexaforbusiness_putinvitationconfiguration.CreatePutinvitationconfigurationTool(cfg),
		tools_x_amz_target_alexaforbusiness_listbusinessreportschedules.CreateListbusinessreportschedulesTool(cfg),
		tools_x_amz_target_alexaforbusiness_listtags.CreateListtagsTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchaddressbooks.CreateSearchaddressbooksTool(cfg),
		tools_x_amz_target_alexaforbusiness_forgetsmarthomeappliances.CreateForgetsmarthomeappliancesTool(cfg),
		tools_x_amz_target_alexaforbusiness_rejectskill.CreateRejectskillTool(cfg),
		tools_x_amz_target_alexaforbusiness_createaddressbook.CreateCreateaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_disassociatecontactfromaddressbook.CreateDisassociatecontactfromaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_getnetworkprofile.CreateGetnetworkprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_updategatewaygroup.CreateUpdategatewaygroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchprofiles.CreateSearchprofilesTool(cfg),
		tools_x_amz_target_alexaforbusiness_getskillgroup.CreateGetskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_listskillsstoreskillsbycategory.CreateListskillsstoreskillsbycategoryTool(cfg),
		tools_x_amz_target_alexaforbusiness_listsmarthomeappliances.CreateListsmarthomeappliancesTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletebusinessreportschedule.CreateDeletebusinessreportscheduleTool(cfg),
		tools_x_amz_target_alexaforbusiness_listskills.CreateListskillsTool(cfg),
		tools_x_amz_target_alexaforbusiness_putconferencepreference.CreatePutconferencepreferenceTool(cfg),
		tools_x_amz_target_alexaforbusiness_disassociateskillfromusers.CreateDisassociateskillfromusersTool(cfg),
		tools_x_amz_target_alexaforbusiness_associateskillwithskillgroup.CreateAssociateskillwithskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_getcontact.CreateGetcontactTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteprofile.CreateDeleteprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_getinvitationconfiguration.CreateGetinvitationconfigurationTool(cfg),
		tools_x_amz_target_alexaforbusiness_disassociateskillfromskillgroup.CreateDisassociateskillfromskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteroomskillparameter.CreateDeleteroomskillparameterTool(cfg),
		tools_x_amz_target_alexaforbusiness_updateconferenceprovider.CreateUpdateconferenceproviderTool(cfg),
		tools_x_amz_target_alexaforbusiness_createnetworkprofile.CreateCreatenetworkprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_getdevice.CreateGetdeviceTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteconferenceprovider.CreateDeleteconferenceproviderTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletecontact.CreateDeletecontactTool(cfg),
		tools_x_amz_target_alexaforbusiness_putroomskillparameter.CreatePutroomskillparameterTool(cfg),
		tools_x_amz_target_alexaforbusiness_sendannouncement.CreateSendannouncementTool(cfg),
		tools_x_amz_target_alexaforbusiness_updatenetworkprofile.CreateUpdatenetworkprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_createconferenceprovider.CreateCreateconferenceproviderTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletegatewaygroup.CreateDeletegatewaygroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchusers.CreateSearchusersTool(cfg),
		tools_x_amz_target_alexaforbusiness_listgateways.CreateListgatewaysTool(cfg),
		tools_x_amz_target_alexaforbusiness_createprofile.CreateCreateprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_listgatewaygroups.CreateListgatewaygroupsTool(cfg),
		tools_x_amz_target_alexaforbusiness_createcontact.CreateCreatecontactTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteuser.CreateDeleteuserTool(cfg),
		tools_x_amz_target_alexaforbusiness_createbusinessreportschedule.CreateCreatebusinessreportscheduleTool(cfg),
		tools_x_amz_target_alexaforbusiness_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_alexaforbusiness_associateskillgroupwithroom.CreateAssociateskillgroupwithroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_listskillsstorecategories.CreateListskillsstorecategoriesTool(cfg),
		tools_x_amz_target_alexaforbusiness_startdevicesync.CreateStartdevicesyncTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletedeviceusagedata.CreateDeletedeviceusagedataTool(cfg),
		tools_x_amz_target_alexaforbusiness_getgatewaygroup.CreateGetgatewaygroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_putskillauthorization.CreatePutskillauthorizationTool(cfg),
		tools_x_amz_target_alexaforbusiness_associatedevicewithnetworkprofile.CreateAssociatedevicewithnetworkprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_creategatewaygroup.CreateCreategatewaygroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_disassociatedevicefromroom.CreateDisassociatedevicefromroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_revokeinvitation.CreateRevokeinvitationTool(cfg),
		tools_x_amz_target_alexaforbusiness_sendinvitation.CreateSendinvitationTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchdevices.CreateSearchdevicesTool(cfg),
		tools_x_amz_target_alexaforbusiness_resolveroom.CreateResolveroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchskillgroups.CreateSearchskillgroupsTool(cfg),
		tools_x_amz_target_alexaforbusiness_createuser.CreateCreateuserTool(cfg),
		tools_x_amz_target_alexaforbusiness_updateskillgroup.CreateUpdateskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_getconferenceprovider.CreateGetconferenceproviderTool(cfg),
		tools_x_amz_target_alexaforbusiness_getaddressbook.CreateGetaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_disassociateskillgroupfromroom.CreateDisassociateskillgroupfromroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_updategateway.CreateUpdategatewayTool(cfg),
		tools_x_amz_target_alexaforbusiness_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_alexaforbusiness_createroom.CreateCreateroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_approveskill.CreateApproveskillTool(cfg),
		tools_x_amz_target_alexaforbusiness_updatecontact.CreateUpdatecontactTool(cfg),
		tools_x_amz_target_alexaforbusiness_registeravsdevice.CreateRegisteravsdeviceTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteaddressbook.CreateDeleteaddressbookTool(cfg),
		tools_x_amz_target_alexaforbusiness_getroomskillparameter.CreateGetroomskillparameterTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteskillauthorization.CreateDeleteskillauthorizationTool(cfg),
		tools_x_amz_target_alexaforbusiness_updateprofile.CreateUpdateprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_associateskillwithusers.CreateAssociateskillwithusersTool(cfg),
		tools_x_amz_target_alexaforbusiness_getconferencepreference.CreateGetconferencepreferenceTool(cfg),
		tools_x_amz_target_alexaforbusiness_searchrooms.CreateSearchroomsTool(cfg),
		tools_x_amz_target_alexaforbusiness_deleteskillgroup.CreateDeleteskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletedevice.CreateDeletedeviceTool(cfg),
		tools_x_amz_target_alexaforbusiness_createskillgroup.CreateCreateskillgroupTool(cfg),
		tools_x_amz_target_alexaforbusiness_associatedevicewithroom.CreateAssociatedevicewithroomTool(cfg),
		tools_x_amz_target_alexaforbusiness_deletenetworkprofile.CreateDeletenetworkprofileTool(cfg),
		tools_x_amz_target_alexaforbusiness_startsmarthomeappliancediscovery.CreateStartsmarthomeappliancediscoveryTool(cfg),
		tools_x_amz_target_alexaforbusiness_updateroom.CreateUpdateroomTool(cfg),
	}
}
