/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets BusinessReportFailureCode
 */
@JsonAdapter(BusinessReportFailureCode.Adapter.class)
public enum BusinessReportFailureCode {
  
  ACCESS_DENIED("ACCESS_DENIED"),
  
  NO_SUCH_BUCKET("NO_SUCH_BUCKET"),
  
  INTERNAL_FAILURE("INTERNAL_FAILURE");

  private String value;

  BusinessReportFailureCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BusinessReportFailureCode fromValue(String value) {
    for (BusinessReportFailureCode b : BusinessReportFailureCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BusinessReportFailureCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final BusinessReportFailureCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BusinessReportFailureCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BusinessReportFailureCode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    BusinessReportFailureCode.fromValue(value);
  }
}

