/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateConferenceProviderResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateConferenceProviderResponse {
  public static final String SERIALIZED_NAME_CONFERENCE_PROVIDER_ARN = "ConferenceProviderArn";
  @SerializedName(SERIALIZED_NAME_CONFERENCE_PROVIDER_ARN)
  @javax.annotation.Nullable
  private String conferenceProviderArn;

  public CreateConferenceProviderResponse() {
  }

  public CreateConferenceProviderResponse conferenceProviderArn(@javax.annotation.Nullable String conferenceProviderArn) {
    this.conferenceProviderArn = conferenceProviderArn;
    return this;
  }

  /**
   * Get conferenceProviderArn
   * @return conferenceProviderArn
   */
  @javax.annotation.Nullable
  public String getConferenceProviderArn() {
    return conferenceProviderArn;
  }

  public void setConferenceProviderArn(@javax.annotation.Nullable String conferenceProviderArn) {
    this.conferenceProviderArn = conferenceProviderArn;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateConferenceProviderResponse createConferenceProviderResponse = (CreateConferenceProviderResponse) o;
    return Objects.equals(this.conferenceProviderArn, createConferenceProviderResponse.conferenceProviderArn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conferenceProviderArn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateConferenceProviderResponse {\n");
    sb.append("    conferenceProviderArn: ").append(toIndentedString(conferenceProviderArn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ConferenceProviderArn");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateConferenceProviderResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateConferenceProviderResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateConferenceProviderResponse is not found in the empty JSON string", CreateConferenceProviderResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateConferenceProviderResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateConferenceProviderResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ConferenceProviderArn`
      if (jsonObj.get("ConferenceProviderArn") != null && !jsonObj.get("ConferenceProviderArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ConferenceProviderArn"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateConferenceProviderResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateConferenceProviderResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateConferenceProviderResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateConferenceProviderResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateConferenceProviderResponse>() {
           @Override
           public void write(JsonWriter out, CreateConferenceProviderResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateConferenceProviderResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateConferenceProviderResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateConferenceProviderResponse
   * @throws IOException if the JSON string is invalid with respect to CreateConferenceProviderResponse
   */
  public static CreateConferenceProviderResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateConferenceProviderResponse.class);
  }

  /**
   * Convert an instance of CreateConferenceProviderResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

