/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.NetworkEapMethod;
import org.openapitools.client.model.NetworkSecurityType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * CreateNetworkProfileRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CreateNetworkProfileRequest {
  public static final String SERIALIZED_NAME_NETWORK_PROFILE_NAME = "NetworkProfileName";
  @SerializedName(SERIALIZED_NAME_NETWORK_PROFILE_NAME)
  @javax.annotation.Nonnull
  private String networkProfileName;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_SSID = "Ssid";
  @SerializedName(SERIALIZED_NAME_SSID)
  @javax.annotation.Nonnull
  private String ssid;

  public static final String SERIALIZED_NAME_SECURITY_TYPE = "SecurityType";
  @SerializedName(SERIALIZED_NAME_SECURITY_TYPE)
  @javax.annotation.Nonnull
  private NetworkSecurityType securityType;

  public static final String SERIALIZED_NAME_EAP_METHOD = "EapMethod";
  @SerializedName(SERIALIZED_NAME_EAP_METHOD)
  @javax.annotation.Nullable
  private NetworkEapMethod eapMethod;

  public static final String SERIALIZED_NAME_CURRENT_PASSWORD = "CurrentPassword";
  @SerializedName(SERIALIZED_NAME_CURRENT_PASSWORD)
  @javax.annotation.Nullable
  private String currentPassword;

  public static final String SERIALIZED_NAME_NEXT_PASSWORD = "NextPassword";
  @SerializedName(SERIALIZED_NAME_NEXT_PASSWORD)
  @javax.annotation.Nullable
  private String nextPassword;

  public static final String SERIALIZED_NAME_CERTIFICATE_AUTHORITY_ARN = "CertificateAuthorityArn";
  @SerializedName(SERIALIZED_NAME_CERTIFICATE_AUTHORITY_ARN)
  @javax.annotation.Nullable
  private String certificateAuthorityArn;

  public static final String SERIALIZED_NAME_TRUST_ANCHORS = "TrustAnchors";
  @SerializedName(SERIALIZED_NAME_TRUST_ANCHORS)
  @javax.annotation.Nullable
  private List trustAnchors;

  public static final String SERIALIZED_NAME_CLIENT_REQUEST_TOKEN = "ClientRequestToken";
  @SerializedName(SERIALIZED_NAME_CLIENT_REQUEST_TOKEN)
  @javax.annotation.Nonnull
  private String clientRequestToken;

  public static final String SERIALIZED_NAME_TAGS = "Tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List tags;

  public CreateNetworkProfileRequest() {
  }

  public CreateNetworkProfileRequest networkProfileName(@javax.annotation.Nonnull String networkProfileName) {
    this.networkProfileName = networkProfileName;
    return this;
  }

  /**
   * Get networkProfileName
   * @return networkProfileName
   */
  @javax.annotation.Nonnull
  public String getNetworkProfileName() {
    return networkProfileName;
  }

  public void setNetworkProfileName(@javax.annotation.Nonnull String networkProfileName) {
    this.networkProfileName = networkProfileName;
  }


  public CreateNetworkProfileRequest description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateNetworkProfileRequest ssid(@javax.annotation.Nonnull String ssid) {
    this.ssid = ssid;
    return this;
  }

  /**
   * Get ssid
   * @return ssid
   */
  @javax.annotation.Nonnull
  public String getSsid() {
    return ssid;
  }

  public void setSsid(@javax.annotation.Nonnull String ssid) {
    this.ssid = ssid;
  }


  public CreateNetworkProfileRequest securityType(@javax.annotation.Nonnull NetworkSecurityType securityType) {
    this.securityType = securityType;
    return this;
  }

  /**
   * Get securityType
   * @return securityType
   */
  @javax.annotation.Nonnull
  public NetworkSecurityType getSecurityType() {
    return securityType;
  }

  public void setSecurityType(@javax.annotation.Nonnull NetworkSecurityType securityType) {
    this.securityType = securityType;
  }


  public CreateNetworkProfileRequest eapMethod(@javax.annotation.Nullable NetworkEapMethod eapMethod) {
    this.eapMethod = eapMethod;
    return this;
  }

  /**
   * Get eapMethod
   * @return eapMethod
   */
  @javax.annotation.Nullable
  public NetworkEapMethod getEapMethod() {
    return eapMethod;
  }

  public void setEapMethod(@javax.annotation.Nullable NetworkEapMethod eapMethod) {
    this.eapMethod = eapMethod;
  }


  public CreateNetworkProfileRequest currentPassword(@javax.annotation.Nullable String currentPassword) {
    this.currentPassword = currentPassword;
    return this;
  }

  /**
   * Get currentPassword
   * @return currentPassword
   */
  @javax.annotation.Nullable
  public String getCurrentPassword() {
    return currentPassword;
  }

  public void setCurrentPassword(@javax.annotation.Nullable String currentPassword) {
    this.currentPassword = currentPassword;
  }


  public CreateNetworkProfileRequest nextPassword(@javax.annotation.Nullable String nextPassword) {
    this.nextPassword = nextPassword;
    return this;
  }

  /**
   * Get nextPassword
   * @return nextPassword
   */
  @javax.annotation.Nullable
  public String getNextPassword() {
    return nextPassword;
  }

  public void setNextPassword(@javax.annotation.Nullable String nextPassword) {
    this.nextPassword = nextPassword;
  }


  public CreateNetworkProfileRequest certificateAuthorityArn(@javax.annotation.Nullable String certificateAuthorityArn) {
    this.certificateAuthorityArn = certificateAuthorityArn;
    return this;
  }

  /**
   * Get certificateAuthorityArn
   * @return certificateAuthorityArn
   */
  @javax.annotation.Nullable
  public String getCertificateAuthorityArn() {
    return certificateAuthorityArn;
  }

  public void setCertificateAuthorityArn(@javax.annotation.Nullable String certificateAuthorityArn) {
    this.certificateAuthorityArn = certificateAuthorityArn;
  }


  public CreateNetworkProfileRequest trustAnchors(@javax.annotation.Nullable List trustAnchors) {
    this.trustAnchors = trustAnchors;
    return this;
  }

  /**
   * Get trustAnchors
   * @return trustAnchors
   */
  @javax.annotation.Nullable
  public List getTrustAnchors() {
    return trustAnchors;
  }

  public void setTrustAnchors(@javax.annotation.Nullable List trustAnchors) {
    this.trustAnchors = trustAnchors;
  }


  public CreateNetworkProfileRequest clientRequestToken(@javax.annotation.Nonnull String clientRequestToken) {
    this.clientRequestToken = clientRequestToken;
    return this;
  }

  /**
   * A unique, user-specified identifier for the request that ensures idempotency.
   * @return clientRequestToken
   */
  @javax.annotation.Nonnull
  public String getClientRequestToken() {
    return clientRequestToken;
  }

  public void setClientRequestToken(@javax.annotation.Nonnull String clientRequestToken) {
    this.clientRequestToken = clientRequestToken;
  }


  public CreateNetworkProfileRequest tags(@javax.annotation.Nullable List tags) {
    this.tags = tags;
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateNetworkProfileRequest createNetworkProfileRequest = (CreateNetworkProfileRequest) o;
    return Objects.equals(this.networkProfileName, createNetworkProfileRequest.networkProfileName) &&
        Objects.equals(this.description, createNetworkProfileRequest.description) &&
        Objects.equals(this.ssid, createNetworkProfileRequest.ssid) &&
        Objects.equals(this.securityType, createNetworkProfileRequest.securityType) &&
        Objects.equals(this.eapMethod, createNetworkProfileRequest.eapMethod) &&
        Objects.equals(this.currentPassword, createNetworkProfileRequest.currentPassword) &&
        Objects.equals(this.nextPassword, createNetworkProfileRequest.nextPassword) &&
        Objects.equals(this.certificateAuthorityArn, createNetworkProfileRequest.certificateAuthorityArn) &&
        Objects.equals(this.trustAnchors, createNetworkProfileRequest.trustAnchors) &&
        Objects.equals(this.clientRequestToken, createNetworkProfileRequest.clientRequestToken) &&
        Objects.equals(this.tags, createNetworkProfileRequest.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkProfileName, description, ssid, securityType, eapMethod, currentPassword, nextPassword, certificateAuthorityArn, trustAnchors, clientRequestToken, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateNetworkProfileRequest {\n");
    sb.append("    networkProfileName: ").append(toIndentedString(networkProfileName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ssid: ").append(toIndentedString(ssid)).append("\n");
    sb.append("    securityType: ").append(toIndentedString(securityType)).append("\n");
    sb.append("    eapMethod: ").append(toIndentedString(eapMethod)).append("\n");
    sb.append("    currentPassword: ").append(toIndentedString(currentPassword)).append("\n");
    sb.append("    nextPassword: ").append(toIndentedString(nextPassword)).append("\n");
    sb.append("    certificateAuthorityArn: ").append(toIndentedString(certificateAuthorityArn)).append("\n");
    sb.append("    trustAnchors: ").append(toIndentedString(trustAnchors)).append("\n");
    sb.append("    clientRequestToken: ").append(toIndentedString(clientRequestToken)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("NetworkProfileName");
    openapiFields.add("Description");
    openapiFields.add("Ssid");
    openapiFields.add("SecurityType");
    openapiFields.add("EapMethod");
    openapiFields.add("CurrentPassword");
    openapiFields.add("NextPassword");
    openapiFields.add("CertificateAuthorityArn");
    openapiFields.add("TrustAnchors");
    openapiFields.add("ClientRequestToken");
    openapiFields.add("Tags");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("NetworkProfileName");
    openapiRequiredFields.add("Ssid");
    openapiRequiredFields.add("SecurityType");
    openapiRequiredFields.add("ClientRequestToken");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateNetworkProfileRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateNetworkProfileRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateNetworkProfileRequest is not found in the empty JSON string", CreateNetworkProfileRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateNetworkProfileRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateNetworkProfileRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateNetworkProfileRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `NetworkProfileName`
      String.validateJsonElement(jsonObj.get("NetworkProfileName"));
      // validate the optional field `Description`
      if (jsonObj.get("Description") != null && !jsonObj.get("Description").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Description"));
      }
      // validate the required field `Ssid`
      String.validateJsonElement(jsonObj.get("Ssid"));
      // validate the required field `SecurityType`
      NetworkSecurityType.validateJsonElement(jsonObj.get("SecurityType"));
      // validate the optional field `EapMethod`
      if (jsonObj.get("EapMethod") != null && !jsonObj.get("EapMethod").isJsonNull()) {
        NetworkEapMethod.validateJsonElement(jsonObj.get("EapMethod"));
      }
      // validate the optional field `CurrentPassword`
      if (jsonObj.get("CurrentPassword") != null && !jsonObj.get("CurrentPassword").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("CurrentPassword"));
      }
      // validate the optional field `NextPassword`
      if (jsonObj.get("NextPassword") != null && !jsonObj.get("NextPassword").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextPassword"));
      }
      // validate the optional field `CertificateAuthorityArn`
      if (jsonObj.get("CertificateAuthorityArn") != null && !jsonObj.get("CertificateAuthorityArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("CertificateAuthorityArn"));
      }
      // validate the optional field `TrustAnchors`
      if (jsonObj.get("TrustAnchors") != null && !jsonObj.get("TrustAnchors").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("TrustAnchors"));
      }
      if (!jsonObj.get("ClientRequestToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ClientRequestToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ClientRequestToken").toString()));
      }
      // validate the optional field `Tags`
      if (jsonObj.get("Tags") != null && !jsonObj.get("Tags").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("Tags"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateNetworkProfileRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateNetworkProfileRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateNetworkProfileRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateNetworkProfileRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateNetworkProfileRequest>() {
           @Override
           public void write(JsonWriter out, CreateNetworkProfileRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateNetworkProfileRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateNetworkProfileRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateNetworkProfileRequest
   * @throws IOException if the JSON string is invalid with respect to CreateNetworkProfileRequest
   */
  public static CreateNetworkProfileRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateNetworkProfileRequest.class);
  }

  /**
   * Convert an instance of CreateNetworkProfileRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

