/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DeleteRoomSkillParameterRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeleteRoomSkillParameterRequest {
  public static final String SERIALIZED_NAME_ROOM_ARN = "RoomArn";
  @SerializedName(SERIALIZED_NAME_ROOM_ARN)
  @javax.annotation.Nullable
  private String roomArn;

  public static final String SERIALIZED_NAME_SKILL_ID = "SkillId";
  @SerializedName(SERIALIZED_NAME_SKILL_ID)
  @javax.annotation.Nonnull
  private String skillId;

  public static final String SERIALIZED_NAME_PARAMETER_KEY = "ParameterKey";
  @SerializedName(SERIALIZED_NAME_PARAMETER_KEY)
  @javax.annotation.Nonnull
  private String parameterKey;

  public DeleteRoomSkillParameterRequest() {
  }

  public DeleteRoomSkillParameterRequest roomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
    return this;
  }

  /**
   * Get roomArn
   * @return roomArn
   */
  @javax.annotation.Nullable
  public String getRoomArn() {
    return roomArn;
  }

  public void setRoomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
  }


  public DeleteRoomSkillParameterRequest skillId(@javax.annotation.Nonnull String skillId) {
    this.skillId = skillId;
    return this;
  }

  /**
   * Get skillId
   * @return skillId
   */
  @javax.annotation.Nonnull
  public String getSkillId() {
    return skillId;
  }

  public void setSkillId(@javax.annotation.Nonnull String skillId) {
    this.skillId = skillId;
  }


  public DeleteRoomSkillParameterRequest parameterKey(@javax.annotation.Nonnull String parameterKey) {
    this.parameterKey = parameterKey;
    return this;
  }

  /**
   * Get parameterKey
   * @return parameterKey
   */
  @javax.annotation.Nonnull
  public String getParameterKey() {
    return parameterKey;
  }

  public void setParameterKey(@javax.annotation.Nonnull String parameterKey) {
    this.parameterKey = parameterKey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteRoomSkillParameterRequest deleteRoomSkillParameterRequest = (DeleteRoomSkillParameterRequest) o;
    return Objects.equals(this.roomArn, deleteRoomSkillParameterRequest.roomArn) &&
        Objects.equals(this.skillId, deleteRoomSkillParameterRequest.skillId) &&
        Objects.equals(this.parameterKey, deleteRoomSkillParameterRequest.parameterKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomArn, skillId, parameterKey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteRoomSkillParameterRequest {\n");
    sb.append("    roomArn: ").append(toIndentedString(roomArn)).append("\n");
    sb.append("    skillId: ").append(toIndentedString(skillId)).append("\n");
    sb.append("    parameterKey: ").append(toIndentedString(parameterKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RoomArn");
    openapiFields.add("SkillId");
    openapiFields.add("ParameterKey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("SkillId");
    openapiRequiredFields.add("ParameterKey");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeleteRoomSkillParameterRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeleteRoomSkillParameterRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeleteRoomSkillParameterRequest is not found in the empty JSON string", DeleteRoomSkillParameterRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeleteRoomSkillParameterRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeleteRoomSkillParameterRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DeleteRoomSkillParameterRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `RoomArn`
      if (jsonObj.get("RoomArn") != null && !jsonObj.get("RoomArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RoomArn"));
      }
      // validate the required field `SkillId`
      String.validateJsonElement(jsonObj.get("SkillId"));
      // validate the required field `ParameterKey`
      String.validateJsonElement(jsonObj.get("ParameterKey"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeleteRoomSkillParameterRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeleteRoomSkillParameterRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeleteRoomSkillParameterRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeleteRoomSkillParameterRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DeleteRoomSkillParameterRequest>() {
           @Override
           public void write(JsonWriter out, DeleteRoomSkillParameterRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeleteRoomSkillParameterRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeleteRoomSkillParameterRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeleteRoomSkillParameterRequest
   * @throws IOException if the JSON string is invalid with respect to DeleteRoomSkillParameterRequest
   */
  public static DeleteRoomSkillParameterRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeleteRoomSkillParameterRequest.class);
  }

  /**
   * Convert an instance of DeleteRoomSkillParameterRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

