/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The details about the developer that published the skill.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeveloperInfo {
  public static final String SERIALIZED_NAME_DEVELOPER_NAME = "DeveloperName";
  @SerializedName(SERIALIZED_NAME_DEVELOPER_NAME)
  @javax.annotation.Nullable
  private String developerName;

  public static final String SERIALIZED_NAME_PRIVACY_POLICY = "PrivacyPolicy";
  @SerializedName(SERIALIZED_NAME_PRIVACY_POLICY)
  @javax.annotation.Nullable
  private String privacyPolicy;

  public static final String SERIALIZED_NAME_EMAIL = "Email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_URL = "Url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private String url;

  public DeveloperInfo() {
  }

  public DeveloperInfo developerName(@javax.annotation.Nullable String developerName) {
    this.developerName = developerName;
    return this;
  }

  /**
   * Get developerName
   * @return developerName
   */
  @javax.annotation.Nullable
  public String getDeveloperName() {
    return developerName;
  }

  public void setDeveloperName(@javax.annotation.Nullable String developerName) {
    this.developerName = developerName;
  }


  public DeveloperInfo privacyPolicy(@javax.annotation.Nullable String privacyPolicy) {
    this.privacyPolicy = privacyPolicy;
    return this;
  }

  /**
   * Get privacyPolicy
   * @return privacyPolicy
   */
  @javax.annotation.Nullable
  public String getPrivacyPolicy() {
    return privacyPolicy;
  }

  public void setPrivacyPolicy(@javax.annotation.Nullable String privacyPolicy) {
    this.privacyPolicy = privacyPolicy;
  }


  public DeveloperInfo email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  public String getEmail() {
    return email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public DeveloperInfo url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeveloperInfo developerInfo = (DeveloperInfo) o;
    return Objects.equals(this.developerName, developerInfo.developerName) &&
        Objects.equals(this.privacyPolicy, developerInfo.privacyPolicy) &&
        Objects.equals(this.email, developerInfo.email) &&
        Objects.equals(this.url, developerInfo.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(developerName, privacyPolicy, email, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeveloperInfo {\n");
    sb.append("    developerName: ").append(toIndentedString(developerName)).append("\n");
    sb.append("    privacyPolicy: ").append(toIndentedString(privacyPolicy)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DeveloperName");
    openapiFields.add("PrivacyPolicy");
    openapiFields.add("Email");
    openapiFields.add("Url");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeveloperInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeveloperInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeveloperInfo is not found in the empty JSON string", DeveloperInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeveloperInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeveloperInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `DeveloperName`
      if (jsonObj.get("DeveloperName") != null && !jsonObj.get("DeveloperName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DeveloperName"));
      }
      // validate the optional field `PrivacyPolicy`
      if (jsonObj.get("PrivacyPolicy") != null && !jsonObj.get("PrivacyPolicy").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("PrivacyPolicy"));
      }
      // validate the optional field `Email`
      if (jsonObj.get("Email") != null && !jsonObj.get("Email").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Email"));
      }
      // validate the optional field `Url`
      if (jsonObj.get("Url") != null && !jsonObj.get("Url").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Url"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeveloperInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeveloperInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeveloperInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeveloperInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<DeveloperInfo>() {
           @Override
           public void write(JsonWriter out, DeveloperInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeveloperInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeveloperInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeveloperInfo
   * @throws IOException if the JSON string is invalid with respect to DeveloperInfo
   */
  public static DeveloperInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeveloperInfo.class);
  }

  /**
   * Convert an instance of DeveloperInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

