/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.DeviceDeviceStatusInfo;
import org.openapitools.client.model.DeviceStatus;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Device attributes.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DeviceData {
  public static final String SERIALIZED_NAME_DEVICE_ARN = "DeviceArn";
  @SerializedName(SERIALIZED_NAME_DEVICE_ARN)
  @javax.annotation.Nullable
  private String deviceArn;

  public static final String SERIALIZED_NAME_DEVICE_SERIAL_NUMBER = "DeviceSerialNumber";
  @SerializedName(SERIALIZED_NAME_DEVICE_SERIAL_NUMBER)
  @javax.annotation.Nullable
  private String deviceSerialNumber;

  public static final String SERIALIZED_NAME_DEVICE_TYPE = "DeviceType";
  @SerializedName(SERIALIZED_NAME_DEVICE_TYPE)
  @javax.annotation.Nullable
  private String deviceType;

  public static final String SERIALIZED_NAME_DEVICE_NAME = "DeviceName";
  @SerializedName(SERIALIZED_NAME_DEVICE_NAME)
  @javax.annotation.Nullable
  private String deviceName;

  public static final String SERIALIZED_NAME_SOFTWARE_VERSION = "SoftwareVersion";
  @SerializedName(SERIALIZED_NAME_SOFTWARE_VERSION)
  @javax.annotation.Nullable
  private String softwareVersion;

  public static final String SERIALIZED_NAME_MAC_ADDRESS = "MacAddress";
  @SerializedName(SERIALIZED_NAME_MAC_ADDRESS)
  @javax.annotation.Nullable
  private String macAddress;

  public static final String SERIALIZED_NAME_DEVICE_STATUS = "DeviceStatus";
  @SerializedName(SERIALIZED_NAME_DEVICE_STATUS)
  @javax.annotation.Nullable
  private DeviceStatus deviceStatus;

  public static final String SERIALIZED_NAME_NETWORK_PROFILE_ARN = "NetworkProfileArn";
  @SerializedName(SERIALIZED_NAME_NETWORK_PROFILE_ARN)
  @javax.annotation.Nullable
  private String networkProfileArn;

  public static final String SERIALIZED_NAME_NETWORK_PROFILE_NAME = "NetworkProfileName";
  @SerializedName(SERIALIZED_NAME_NETWORK_PROFILE_NAME)
  @javax.annotation.Nullable
  private String networkProfileName;

  public static final String SERIALIZED_NAME_ROOM_ARN = "RoomArn";
  @SerializedName(SERIALIZED_NAME_ROOM_ARN)
  @javax.annotation.Nullable
  private String roomArn;

  public static final String SERIALIZED_NAME_ROOM_NAME = "RoomName";
  @SerializedName(SERIALIZED_NAME_ROOM_NAME)
  @javax.annotation.Nullable
  private String roomName;

  public static final String SERIALIZED_NAME_DEVICE_STATUS_INFO = "DeviceStatusInfo";
  @SerializedName(SERIALIZED_NAME_DEVICE_STATUS_INFO)
  @javax.annotation.Nullable
  private DeviceDeviceStatusInfo deviceStatusInfo;

  public static final String SERIALIZED_NAME_CREATED_TIME = "CreatedTime";
  @SerializedName(SERIALIZED_NAME_CREATED_TIME)
  @javax.annotation.Nullable
  private OffsetDateTime createdTime;

  public DeviceData() {
  }

  public DeviceData deviceArn(@javax.annotation.Nullable String deviceArn) {
    this.deviceArn = deviceArn;
    return this;
  }

  /**
   * Get deviceArn
   * @return deviceArn
   */
  @javax.annotation.Nullable
  public String getDeviceArn() {
    return deviceArn;
  }

  public void setDeviceArn(@javax.annotation.Nullable String deviceArn) {
    this.deviceArn = deviceArn;
  }


  public DeviceData deviceSerialNumber(@javax.annotation.Nullable String deviceSerialNumber) {
    this.deviceSerialNumber = deviceSerialNumber;
    return this;
  }

  /**
   * Get deviceSerialNumber
   * @return deviceSerialNumber
   */
  @javax.annotation.Nullable
  public String getDeviceSerialNumber() {
    return deviceSerialNumber;
  }

  public void setDeviceSerialNumber(@javax.annotation.Nullable String deviceSerialNumber) {
    this.deviceSerialNumber = deviceSerialNumber;
  }


  public DeviceData deviceType(@javax.annotation.Nullable String deviceType) {
    this.deviceType = deviceType;
    return this;
  }

  /**
   * Get deviceType
   * @return deviceType
   */
  @javax.annotation.Nullable
  public String getDeviceType() {
    return deviceType;
  }

  public void setDeviceType(@javax.annotation.Nullable String deviceType) {
    this.deviceType = deviceType;
  }


  public DeviceData deviceName(@javax.annotation.Nullable String deviceName) {
    this.deviceName = deviceName;
    return this;
  }

  /**
   * Get deviceName
   * @return deviceName
   */
  @javax.annotation.Nullable
  public String getDeviceName() {
    return deviceName;
  }

  public void setDeviceName(@javax.annotation.Nullable String deviceName) {
    this.deviceName = deviceName;
  }


  public DeviceData softwareVersion(@javax.annotation.Nullable String softwareVersion) {
    this.softwareVersion = softwareVersion;
    return this;
  }

  /**
   * Get softwareVersion
   * @return softwareVersion
   */
  @javax.annotation.Nullable
  public String getSoftwareVersion() {
    return softwareVersion;
  }

  public void setSoftwareVersion(@javax.annotation.Nullable String softwareVersion) {
    this.softwareVersion = softwareVersion;
  }


  public DeviceData macAddress(@javax.annotation.Nullable String macAddress) {
    this.macAddress = macAddress;
    return this;
  }

  /**
   * Get macAddress
   * @return macAddress
   */
  @javax.annotation.Nullable
  public String getMacAddress() {
    return macAddress;
  }

  public void setMacAddress(@javax.annotation.Nullable String macAddress) {
    this.macAddress = macAddress;
  }


  public DeviceData deviceStatus(@javax.annotation.Nullable DeviceStatus deviceStatus) {
    this.deviceStatus = deviceStatus;
    return this;
  }

  /**
   * Get deviceStatus
   * @return deviceStatus
   */
  @javax.annotation.Nullable
  public DeviceStatus getDeviceStatus() {
    return deviceStatus;
  }

  public void setDeviceStatus(@javax.annotation.Nullable DeviceStatus deviceStatus) {
    this.deviceStatus = deviceStatus;
  }


  public DeviceData networkProfileArn(@javax.annotation.Nullable String networkProfileArn) {
    this.networkProfileArn = networkProfileArn;
    return this;
  }

  /**
   * Get networkProfileArn
   * @return networkProfileArn
   */
  @javax.annotation.Nullable
  public String getNetworkProfileArn() {
    return networkProfileArn;
  }

  public void setNetworkProfileArn(@javax.annotation.Nullable String networkProfileArn) {
    this.networkProfileArn = networkProfileArn;
  }


  public DeviceData networkProfileName(@javax.annotation.Nullable String networkProfileName) {
    this.networkProfileName = networkProfileName;
    return this;
  }

  /**
   * Get networkProfileName
   * @return networkProfileName
   */
  @javax.annotation.Nullable
  public String getNetworkProfileName() {
    return networkProfileName;
  }

  public void setNetworkProfileName(@javax.annotation.Nullable String networkProfileName) {
    this.networkProfileName = networkProfileName;
  }


  public DeviceData roomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
    return this;
  }

  /**
   * Get roomArn
   * @return roomArn
   */
  @javax.annotation.Nullable
  public String getRoomArn() {
    return roomArn;
  }

  public void setRoomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
  }


  public DeviceData roomName(@javax.annotation.Nullable String roomName) {
    this.roomName = roomName;
    return this;
  }

  /**
   * Get roomName
   * @return roomName
   */
  @javax.annotation.Nullable
  public String getRoomName() {
    return roomName;
  }

  public void setRoomName(@javax.annotation.Nullable String roomName) {
    this.roomName = roomName;
  }


  public DeviceData deviceStatusInfo(@javax.annotation.Nullable DeviceDeviceStatusInfo deviceStatusInfo) {
    this.deviceStatusInfo = deviceStatusInfo;
    return this;
  }

  /**
   * Get deviceStatusInfo
   * @return deviceStatusInfo
   */
  @javax.annotation.Nullable
  public DeviceDeviceStatusInfo getDeviceStatusInfo() {
    return deviceStatusInfo;
  }

  public void setDeviceStatusInfo(@javax.annotation.Nullable DeviceDeviceStatusInfo deviceStatusInfo) {
    this.deviceStatusInfo = deviceStatusInfo;
  }


  public DeviceData createdTime(@javax.annotation.Nullable OffsetDateTime createdTime) {
    this.createdTime = createdTime;
    return this;
  }

  /**
   * Get createdTime
   * @return createdTime
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(@javax.annotation.Nullable OffsetDateTime createdTime) {
    this.createdTime = createdTime;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceData deviceData = (DeviceData) o;
    return Objects.equals(this.deviceArn, deviceData.deviceArn) &&
        Objects.equals(this.deviceSerialNumber, deviceData.deviceSerialNumber) &&
        Objects.equals(this.deviceType, deviceData.deviceType) &&
        Objects.equals(this.deviceName, deviceData.deviceName) &&
        Objects.equals(this.softwareVersion, deviceData.softwareVersion) &&
        Objects.equals(this.macAddress, deviceData.macAddress) &&
        Objects.equals(this.deviceStatus, deviceData.deviceStatus) &&
        Objects.equals(this.networkProfileArn, deviceData.networkProfileArn) &&
        Objects.equals(this.networkProfileName, deviceData.networkProfileName) &&
        Objects.equals(this.roomArn, deviceData.roomArn) &&
        Objects.equals(this.roomName, deviceData.roomName) &&
        Objects.equals(this.deviceStatusInfo, deviceData.deviceStatusInfo) &&
        Objects.equals(this.createdTime, deviceData.createdTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceArn, deviceSerialNumber, deviceType, deviceName, softwareVersion, macAddress, deviceStatus, networkProfileArn, networkProfileName, roomArn, roomName, deviceStatusInfo, createdTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceData {\n");
    sb.append("    deviceArn: ").append(toIndentedString(deviceArn)).append("\n");
    sb.append("    deviceSerialNumber: ").append(toIndentedString(deviceSerialNumber)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    deviceName: ").append(toIndentedString(deviceName)).append("\n");
    sb.append("    softwareVersion: ").append(toIndentedString(softwareVersion)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    deviceStatus: ").append(toIndentedString(deviceStatus)).append("\n");
    sb.append("    networkProfileArn: ").append(toIndentedString(networkProfileArn)).append("\n");
    sb.append("    networkProfileName: ").append(toIndentedString(networkProfileName)).append("\n");
    sb.append("    roomArn: ").append(toIndentedString(roomArn)).append("\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    deviceStatusInfo: ").append(toIndentedString(deviceStatusInfo)).append("\n");
    sb.append("    createdTime: ").append(toIndentedString(createdTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DeviceArn");
    openapiFields.add("DeviceSerialNumber");
    openapiFields.add("DeviceType");
    openapiFields.add("DeviceName");
    openapiFields.add("SoftwareVersion");
    openapiFields.add("MacAddress");
    openapiFields.add("DeviceStatus");
    openapiFields.add("NetworkProfileArn");
    openapiFields.add("NetworkProfileName");
    openapiFields.add("RoomArn");
    openapiFields.add("RoomName");
    openapiFields.add("DeviceStatusInfo");
    openapiFields.add("CreatedTime");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeviceData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeviceData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeviceData is not found in the empty JSON string", DeviceData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeviceData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeviceData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `DeviceArn`
      if (jsonObj.get("DeviceArn") != null && !jsonObj.get("DeviceArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DeviceArn"));
      }
      // validate the optional field `DeviceSerialNumber`
      if (jsonObj.get("DeviceSerialNumber") != null && !jsonObj.get("DeviceSerialNumber").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DeviceSerialNumber"));
      }
      // validate the optional field `DeviceType`
      if (jsonObj.get("DeviceType") != null && !jsonObj.get("DeviceType").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DeviceType"));
      }
      // validate the optional field `DeviceName`
      if (jsonObj.get("DeviceName") != null && !jsonObj.get("DeviceName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("DeviceName"));
      }
      // validate the optional field `SoftwareVersion`
      if (jsonObj.get("SoftwareVersion") != null && !jsonObj.get("SoftwareVersion").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("SoftwareVersion"));
      }
      // validate the optional field `MacAddress`
      if (jsonObj.get("MacAddress") != null && !jsonObj.get("MacAddress").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("MacAddress"));
      }
      // validate the optional field `DeviceStatus`
      if (jsonObj.get("DeviceStatus") != null && !jsonObj.get("DeviceStatus").isJsonNull()) {
        DeviceStatus.validateJsonElement(jsonObj.get("DeviceStatus"));
      }
      // validate the optional field `NetworkProfileArn`
      if (jsonObj.get("NetworkProfileArn") != null && !jsonObj.get("NetworkProfileArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NetworkProfileArn"));
      }
      // validate the optional field `NetworkProfileName`
      if (jsonObj.get("NetworkProfileName") != null && !jsonObj.get("NetworkProfileName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NetworkProfileName"));
      }
      // validate the optional field `RoomArn`
      if (jsonObj.get("RoomArn") != null && !jsonObj.get("RoomArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RoomArn"));
      }
      // validate the optional field `RoomName`
      if (jsonObj.get("RoomName") != null && !jsonObj.get("RoomName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RoomName"));
      }
      // validate the optional field `DeviceStatusInfo`
      if (jsonObj.get("DeviceStatusInfo") != null && !jsonObj.get("DeviceStatusInfo").isJsonNull()) {
        DeviceDeviceStatusInfo.validateJsonElement(jsonObj.get("DeviceStatusInfo"));
      }
      // validate the optional field `CreatedTime`
      if (jsonObj.get("CreatedTime") != null && !jsonObj.get("CreatedTime").isJsonNull()) {
        OffsetDateTime.validateJsonElement(jsonObj.get("CreatedTime"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceData.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceData>() {
           @Override
           public void write(JsonWriter out, DeviceData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeviceData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeviceData
   * @throws IOException if the JSON string is invalid with respect to DeviceData
   */
  public static DeviceData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceData.class);
  }

  /**
   * Convert an instance of DeviceData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

