/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.GetConferenceProviderResponseConferenceProvider;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetConferenceProviderResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetConferenceProviderResponse {
  public static final String SERIALIZED_NAME_CONFERENCE_PROVIDER = "ConferenceProvider";
  @SerializedName(SERIALIZED_NAME_CONFERENCE_PROVIDER)
  @javax.annotation.Nullable
  private GetConferenceProviderResponseConferenceProvider conferenceProvider;

  public GetConferenceProviderResponse() {
  }

  public GetConferenceProviderResponse conferenceProvider(@javax.annotation.Nullable GetConferenceProviderResponseConferenceProvider conferenceProvider) {
    this.conferenceProvider = conferenceProvider;
    return this;
  }

  /**
   * Get conferenceProvider
   * @return conferenceProvider
   */
  @javax.annotation.Nullable
  public GetConferenceProviderResponseConferenceProvider getConferenceProvider() {
    return conferenceProvider;
  }

  public void setConferenceProvider(@javax.annotation.Nullable GetConferenceProviderResponseConferenceProvider conferenceProvider) {
    this.conferenceProvider = conferenceProvider;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConferenceProviderResponse getConferenceProviderResponse = (GetConferenceProviderResponse) o;
    return Objects.equals(this.conferenceProvider, getConferenceProviderResponse.conferenceProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conferenceProvider);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConferenceProviderResponse {\n");
    sb.append("    conferenceProvider: ").append(toIndentedString(conferenceProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ConferenceProvider");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetConferenceProviderResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetConferenceProviderResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetConferenceProviderResponse is not found in the empty JSON string", GetConferenceProviderResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetConferenceProviderResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetConferenceProviderResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ConferenceProvider`
      if (jsonObj.get("ConferenceProvider") != null && !jsonObj.get("ConferenceProvider").isJsonNull()) {
        GetConferenceProviderResponseConferenceProvider.validateJsonElement(jsonObj.get("ConferenceProvider"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetConferenceProviderResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetConferenceProviderResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetConferenceProviderResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetConferenceProviderResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetConferenceProviderResponse>() {
           @Override
           public void write(JsonWriter out, GetConferenceProviderResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetConferenceProviderResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetConferenceProviderResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetConferenceProviderResponse
   * @throws IOException if the JSON string is invalid with respect to GetConferenceProviderResponse
   */
  public static GetConferenceProviderResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetConferenceProviderResponse.class);
  }

  /**
   * Convert an instance of GetConferenceProviderResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

