/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * GetInvitationConfigurationResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class GetInvitationConfigurationResponse {
  public static final String SERIALIZED_NAME_ORGANIZATION_NAME = "OrganizationName";
  @SerializedName(SERIALIZED_NAME_ORGANIZATION_NAME)
  @javax.annotation.Nullable
  private String organizationName;

  public static final String SERIALIZED_NAME_CONTACT_EMAIL = "ContactEmail";
  @SerializedName(SERIALIZED_NAME_CONTACT_EMAIL)
  @javax.annotation.Nullable
  private String contactEmail;

  public static final String SERIALIZED_NAME_PRIVATE_SKILL_IDS = "PrivateSkillIds";
  @SerializedName(SERIALIZED_NAME_PRIVATE_SKILL_IDS)
  @javax.annotation.Nullable
  private List privateSkillIds;

  public GetInvitationConfigurationResponse() {
  }

  public GetInvitationConfigurationResponse organizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * Get organizationName
   * @return organizationName
   */
  @javax.annotation.Nullable
  public String getOrganizationName() {
    return organizationName;
  }

  public void setOrganizationName(@javax.annotation.Nullable String organizationName) {
    this.organizationName = organizationName;
  }


  public GetInvitationConfigurationResponse contactEmail(@javax.annotation.Nullable String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

  /**
   * Get contactEmail
   * @return contactEmail
   */
  @javax.annotation.Nullable
  public String getContactEmail() {
    return contactEmail;
  }

  public void setContactEmail(@javax.annotation.Nullable String contactEmail) {
    this.contactEmail = contactEmail;
  }


  public GetInvitationConfigurationResponse privateSkillIds(@javax.annotation.Nullable List privateSkillIds) {
    this.privateSkillIds = privateSkillIds;
    return this;
  }

  /**
   * Get privateSkillIds
   * @return privateSkillIds
   */
  @javax.annotation.Nullable
  public List getPrivateSkillIds() {
    return privateSkillIds;
  }

  public void setPrivateSkillIds(@javax.annotation.Nullable List privateSkillIds) {
    this.privateSkillIds = privateSkillIds;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInvitationConfigurationResponse getInvitationConfigurationResponse = (GetInvitationConfigurationResponse) o;
    return Objects.equals(this.organizationName, getInvitationConfigurationResponse.organizationName) &&
        Objects.equals(this.contactEmail, getInvitationConfigurationResponse.contactEmail) &&
        Objects.equals(this.privateSkillIds, getInvitationConfigurationResponse.privateSkillIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organizationName, contactEmail, privateSkillIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInvitationConfigurationResponse {\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    contactEmail: ").append(toIndentedString(contactEmail)).append("\n");
    sb.append("    privateSkillIds: ").append(toIndentedString(privateSkillIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("OrganizationName");
    openapiFields.add("ContactEmail");
    openapiFields.add("PrivateSkillIds");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GetInvitationConfigurationResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GetInvitationConfigurationResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetInvitationConfigurationResponse is not found in the empty JSON string", GetInvitationConfigurationResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GetInvitationConfigurationResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetInvitationConfigurationResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `OrganizationName`
      if (jsonObj.get("OrganizationName") != null && !jsonObj.get("OrganizationName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("OrganizationName"));
      }
      // validate the optional field `ContactEmail`
      if (jsonObj.get("ContactEmail") != null && !jsonObj.get("ContactEmail").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ContactEmail"));
      }
      // validate the optional field `PrivateSkillIds`
      if (jsonObj.get("PrivateSkillIds") != null && !jsonObj.get("PrivateSkillIds").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("PrivateSkillIds"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetInvitationConfigurationResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetInvitationConfigurationResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetInvitationConfigurationResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetInvitationConfigurationResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GetInvitationConfigurationResponse>() {
           @Override
           public void write(JsonWriter out, GetInvitationConfigurationResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetInvitationConfigurationResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GetInvitationConfigurationResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GetInvitationConfigurationResponse
   * @throws IOException if the JSON string is invalid with respect to GetInvitationConfigurationResponse
   */
  public static GetInvitationConfigurationResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetInvitationConfigurationResponse.class);
  }

  /**
   * Convert an instance of GetInvitationConfigurationResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

