/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.EnablementTypeFilter;
import org.openapitools.client.model.SkillTypeFilter;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ListSkillsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ListSkillsRequest {
  public static final String SERIALIZED_NAME_SKILL_GROUP_ARN = "SkillGroupArn";
  @SerializedName(SERIALIZED_NAME_SKILL_GROUP_ARN)
  @javax.annotation.Nullable
  private String skillGroupArn;

  public static final String SERIALIZED_NAME_ENABLEMENT_TYPE = "EnablementType";
  @SerializedName(SERIALIZED_NAME_ENABLEMENT_TYPE)
  @javax.annotation.Nullable
  private EnablementTypeFilter enablementType;

  public static final String SERIALIZED_NAME_SKILL_TYPE = "SkillType";
  @SerializedName(SERIALIZED_NAME_SKILL_TYPE)
  @javax.annotation.Nullable
  private SkillTypeFilter skillType;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "NextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public static final String SERIALIZED_NAME_MAX_RESULTS = "MaxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public ListSkillsRequest() {
  }

  public ListSkillsRequest skillGroupArn(@javax.annotation.Nullable String skillGroupArn) {
    this.skillGroupArn = skillGroupArn;
    return this;
  }

  /**
   * Get skillGroupArn
   * @return skillGroupArn
   */
  @javax.annotation.Nullable
  public String getSkillGroupArn() {
    return skillGroupArn;
  }

  public void setSkillGroupArn(@javax.annotation.Nullable String skillGroupArn) {
    this.skillGroupArn = skillGroupArn;
  }


  public ListSkillsRequest enablementType(@javax.annotation.Nullable EnablementTypeFilter enablementType) {
    this.enablementType = enablementType;
    return this;
  }

  /**
   * Get enablementType
   * @return enablementType
   */
  @javax.annotation.Nullable
  public EnablementTypeFilter getEnablementType() {
    return enablementType;
  }

  public void setEnablementType(@javax.annotation.Nullable EnablementTypeFilter enablementType) {
    this.enablementType = enablementType;
  }


  public ListSkillsRequest skillType(@javax.annotation.Nullable SkillTypeFilter skillType) {
    this.skillType = skillType;
    return this;
  }

  /**
   * Get skillType
   * @return skillType
   */
  @javax.annotation.Nullable
  public SkillTypeFilter getSkillType() {
    return skillType;
  }

  public void setSkillType(@javax.annotation.Nullable SkillTypeFilter skillType) {
    this.skillType = skillType;
  }


  public ListSkillsRequest nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }


  public ListSkillsRequest maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   * Get maxResults
   * @return maxResults
   */
  @javax.annotation.Nullable
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListSkillsRequest listSkillsRequest = (ListSkillsRequest) o;
    return Objects.equals(this.skillGroupArn, listSkillsRequest.skillGroupArn) &&
        Objects.equals(this.enablementType, listSkillsRequest.enablementType) &&
        Objects.equals(this.skillType, listSkillsRequest.skillType) &&
        Objects.equals(this.nextToken, listSkillsRequest.nextToken) &&
        Objects.equals(this.maxResults, listSkillsRequest.maxResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skillGroupArn, enablementType, skillType, nextToken, maxResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListSkillsRequest {\n");
    sb.append("    skillGroupArn: ").append(toIndentedString(skillGroupArn)).append("\n");
    sb.append("    enablementType: ").append(toIndentedString(enablementType)).append("\n");
    sb.append("    skillType: ").append(toIndentedString(skillType)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("SkillGroupArn");
    openapiFields.add("EnablementType");
    openapiFields.add("SkillType");
    openapiFields.add("NextToken");
    openapiFields.add("MaxResults");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListSkillsRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListSkillsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListSkillsRequest is not found in the empty JSON string", ListSkillsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListSkillsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListSkillsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `SkillGroupArn`
      if (jsonObj.get("SkillGroupArn") != null && !jsonObj.get("SkillGroupArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("SkillGroupArn"));
      }
      // validate the optional field `EnablementType`
      if (jsonObj.get("EnablementType") != null && !jsonObj.get("EnablementType").isJsonNull()) {
        EnablementTypeFilter.validateJsonElement(jsonObj.get("EnablementType"));
      }
      // validate the optional field `SkillType`
      if (jsonObj.get("SkillType") != null && !jsonObj.get("SkillType").isJsonNull()) {
        SkillTypeFilter.validateJsonElement(jsonObj.get("SkillType"));
      }
      // validate the optional field `NextToken`
      if (jsonObj.get("NextToken") != null && !jsonObj.get("NextToken").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("NextToken"));
      }
      // validate the optional field `MaxResults`
      if (jsonObj.get("MaxResults") != null && !jsonObj.get("MaxResults").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("MaxResults"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListSkillsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListSkillsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListSkillsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListSkillsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ListSkillsRequest>() {
           @Override
           public void write(JsonWriter out, ListSkillsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListSkillsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListSkillsRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListSkillsRequest
   * @throws IOException if the JSON string is invalid with respect to ListSkillsRequest
   */
  public static ListSkillsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListSkillsRequest.class);
  }

  /**
   * Convert an instance of ListSkillsRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

