/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.RequirePin;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * &lt;p&gt;The values that indicate whether a pin is always required (YES), never required (NO), or OPTIONAL.&lt;/p&gt; &lt;ul&gt; &lt;li&gt; &lt;p&gt;If YES, Alexa will always ask for a meeting pin.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;If NO, Alexa will never ask for a meeting pin.&lt;/p&gt; &lt;/li&gt; &lt;li&gt; &lt;p&gt;If OPTIONAL, Alexa will ask if you have a meeting pin and if the customer responds with yes, it will ask for the meeting pin.&lt;/p&gt; &lt;/li&gt; &lt;/ul&gt;
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class MeetingSetting {
  public static final String SERIALIZED_NAME_REQUIRE_PIN = "RequirePin";
  @SerializedName(SERIALIZED_NAME_REQUIRE_PIN)
  @javax.annotation.Nonnull
  private RequirePin requirePin;

  public MeetingSetting() {
  }

  public MeetingSetting requirePin(@javax.annotation.Nonnull RequirePin requirePin) {
    this.requirePin = requirePin;
    return this;
  }

  /**
   * Get requirePin
   * @return requirePin
   */
  @javax.annotation.Nonnull
  public RequirePin getRequirePin() {
    return requirePin;
  }

  public void setRequirePin(@javax.annotation.Nonnull RequirePin requirePin) {
    this.requirePin = requirePin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeetingSetting meetingSetting = (MeetingSetting) o;
    return Objects.equals(this.requirePin, meetingSetting.requirePin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requirePin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeetingSetting {\n");
    sb.append("    requirePin: ").append(toIndentedString(requirePin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RequirePin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("RequirePin");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MeetingSetting
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MeetingSetting.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MeetingSetting is not found in the empty JSON string", MeetingSetting.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MeetingSetting.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MeetingSetting` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MeetingSetting.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `RequirePin`
      RequirePin.validateJsonElement(jsonObj.get("RequirePin"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MeetingSetting.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MeetingSetting' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MeetingSetting> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MeetingSetting.class));

       return (TypeAdapter<T>) new TypeAdapter<MeetingSetting>() {
           @Override
           public void write(JsonWriter out, MeetingSetting value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MeetingSetting read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MeetingSetting given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MeetingSetting
   * @throws IOException if the JSON string is invalid with respect to MeetingSetting
   */
  public static MeetingSetting fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MeetingSetting.class);
  }

  /**
   * Convert an instance of MeetingSetting to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

