/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PhoneNumberType
 */
@JsonAdapter(PhoneNumberType.Adapter.class)
public enum PhoneNumberType {
  
  MOBILE("MOBILE"),
  
  WORK("WORK"),
  
  HOME("HOME");

  private String value;

  PhoneNumberType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PhoneNumberType fromValue(String value) {
    for (PhoneNumberType b : PhoneNumberType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PhoneNumberType> {
    @Override
    public void write(final JsonWriter jsonWriter, final PhoneNumberType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PhoneNumberType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PhoneNumberType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PhoneNumberType.fromValue(value);
  }
}

