/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The information for public switched telephone network (PSTN) conferencing.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class PSTNDialIn {
  public static final String SERIALIZED_NAME_COUNTRY_CODE = "CountryCode";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  @javax.annotation.Nonnull
  private String countryCode;

  public static final String SERIALIZED_NAME_PHONE_NUMBER = "PhoneNumber";
  @SerializedName(SERIALIZED_NAME_PHONE_NUMBER)
  @javax.annotation.Nonnull
  private String phoneNumber;

  public static final String SERIALIZED_NAME_ONE_CLICK_ID_DELAY = "OneClickIdDelay";
  @SerializedName(SERIALIZED_NAME_ONE_CLICK_ID_DELAY)
  @javax.annotation.Nonnull
  private String oneClickIdDelay;

  public static final String SERIALIZED_NAME_ONE_CLICK_PIN_DELAY = "OneClickPinDelay";
  @SerializedName(SERIALIZED_NAME_ONE_CLICK_PIN_DELAY)
  @javax.annotation.Nonnull
  private String oneClickPinDelay;

  public PSTNDialIn() {
  }

  public PSTNDialIn countryCode(@javax.annotation.Nonnull String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Get countryCode
   * @return countryCode
   */
  @javax.annotation.Nonnull
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(@javax.annotation.Nonnull String countryCode) {
    this.countryCode = countryCode;
  }


  public PSTNDialIn phoneNumber(@javax.annotation.Nonnull String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nonnull
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(@javax.annotation.Nonnull String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public PSTNDialIn oneClickIdDelay(@javax.annotation.Nonnull String oneClickIdDelay) {
    this.oneClickIdDelay = oneClickIdDelay;
    return this;
  }

  /**
   * Get oneClickIdDelay
   * @return oneClickIdDelay
   */
  @javax.annotation.Nonnull
  public String getOneClickIdDelay() {
    return oneClickIdDelay;
  }

  public void setOneClickIdDelay(@javax.annotation.Nonnull String oneClickIdDelay) {
    this.oneClickIdDelay = oneClickIdDelay;
  }


  public PSTNDialIn oneClickPinDelay(@javax.annotation.Nonnull String oneClickPinDelay) {
    this.oneClickPinDelay = oneClickPinDelay;
    return this;
  }

  /**
   * Get oneClickPinDelay
   * @return oneClickPinDelay
   */
  @javax.annotation.Nonnull
  public String getOneClickPinDelay() {
    return oneClickPinDelay;
  }

  public void setOneClickPinDelay(@javax.annotation.Nonnull String oneClickPinDelay) {
    this.oneClickPinDelay = oneClickPinDelay;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PSTNDialIn psTNDialIn = (PSTNDialIn) o;
    return Objects.equals(this.countryCode, psTNDialIn.countryCode) &&
        Objects.equals(this.phoneNumber, psTNDialIn.phoneNumber) &&
        Objects.equals(this.oneClickIdDelay, psTNDialIn.oneClickIdDelay) &&
        Objects.equals(this.oneClickPinDelay, psTNDialIn.oneClickPinDelay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(countryCode, phoneNumber, oneClickIdDelay, oneClickPinDelay);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PSTNDialIn {\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    oneClickIdDelay: ").append(toIndentedString(oneClickIdDelay)).append("\n");
    sb.append("    oneClickPinDelay: ").append(toIndentedString(oneClickPinDelay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CountryCode");
    openapiFields.add("PhoneNumber");
    openapiFields.add("OneClickIdDelay");
    openapiFields.add("OneClickPinDelay");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("CountryCode");
    openapiRequiredFields.add("PhoneNumber");
    openapiRequiredFields.add("OneClickIdDelay");
    openapiRequiredFields.add("OneClickPinDelay");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PSTNDialIn
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PSTNDialIn.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PSTNDialIn is not found in the empty JSON string", PSTNDialIn.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PSTNDialIn.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PSTNDialIn` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PSTNDialIn.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `CountryCode`
      String.validateJsonElement(jsonObj.get("CountryCode"));
      // validate the required field `PhoneNumber`
      String.validateJsonElement(jsonObj.get("PhoneNumber"));
      // validate the required field `OneClickIdDelay`
      String.validateJsonElement(jsonObj.get("OneClickIdDelay"));
      // validate the required field `OneClickPinDelay`
      String.validateJsonElement(jsonObj.get("OneClickPinDelay"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PSTNDialIn.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PSTNDialIn' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PSTNDialIn> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PSTNDialIn.class));

       return (TypeAdapter<T>) new TypeAdapter<PSTNDialIn>() {
           @Override
           public void write(JsonWriter out, PSTNDialIn value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PSTNDialIn read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PSTNDialIn given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PSTNDialIn
   * @throws IOException if the JSON string is invalid with respect to PSTNDialIn
   */
  public static PSTNDialIn fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PSTNDialIn.class);
  }

  /**
   * Convert an instance of PSTNDialIn to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

