/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ResolveRoomResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ResolveRoomResponse {
  public static final String SERIALIZED_NAME_ROOM_ARN = "RoomArn";
  @SerializedName(SERIALIZED_NAME_ROOM_ARN)
  @javax.annotation.Nullable
  private String roomArn;

  public static final String SERIALIZED_NAME_ROOM_NAME = "RoomName";
  @SerializedName(SERIALIZED_NAME_ROOM_NAME)
  @javax.annotation.Nullable
  private String roomName;

  public static final String SERIALIZED_NAME_ROOM_SKILL_PARAMETERS = "RoomSkillParameters";
  @SerializedName(SERIALIZED_NAME_ROOM_SKILL_PARAMETERS)
  @javax.annotation.Nullable
  private List roomSkillParameters;

  public ResolveRoomResponse() {
  }

  public ResolveRoomResponse roomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
    return this;
  }

  /**
   * Get roomArn
   * @return roomArn
   */
  @javax.annotation.Nullable
  public String getRoomArn() {
    return roomArn;
  }

  public void setRoomArn(@javax.annotation.Nullable String roomArn) {
    this.roomArn = roomArn;
  }


  public ResolveRoomResponse roomName(@javax.annotation.Nullable String roomName) {
    this.roomName = roomName;
    return this;
  }

  /**
   * Get roomName
   * @return roomName
   */
  @javax.annotation.Nullable
  public String getRoomName() {
    return roomName;
  }

  public void setRoomName(@javax.annotation.Nullable String roomName) {
    this.roomName = roomName;
  }


  public ResolveRoomResponse roomSkillParameters(@javax.annotation.Nullable List roomSkillParameters) {
    this.roomSkillParameters = roomSkillParameters;
    return this;
  }

  /**
   * Get roomSkillParameters
   * @return roomSkillParameters
   */
  @javax.annotation.Nullable
  public List getRoomSkillParameters() {
    return roomSkillParameters;
  }

  public void setRoomSkillParameters(@javax.annotation.Nullable List roomSkillParameters) {
    this.roomSkillParameters = roomSkillParameters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResolveRoomResponse resolveRoomResponse = (ResolveRoomResponse) o;
    return Objects.equals(this.roomArn, resolveRoomResponse.roomArn) &&
        Objects.equals(this.roomName, resolveRoomResponse.roomName) &&
        Objects.equals(this.roomSkillParameters, resolveRoomResponse.roomSkillParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomArn, roomName, roomSkillParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResolveRoomResponse {\n");
    sb.append("    roomArn: ").append(toIndentedString(roomArn)).append("\n");
    sb.append("    roomName: ").append(toIndentedString(roomName)).append("\n");
    sb.append("    roomSkillParameters: ").append(toIndentedString(roomSkillParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RoomArn");
    openapiFields.add("RoomName");
    openapiFields.add("RoomSkillParameters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ResolveRoomResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ResolveRoomResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ResolveRoomResponse is not found in the empty JSON string", ResolveRoomResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ResolveRoomResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ResolveRoomResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `RoomArn`
      if (jsonObj.get("RoomArn") != null && !jsonObj.get("RoomArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RoomArn"));
      }
      // validate the optional field `RoomName`
      if (jsonObj.get("RoomName") != null && !jsonObj.get("RoomName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("RoomName"));
      }
      // validate the optional field `RoomSkillParameters`
      if (jsonObj.get("RoomSkillParameters") != null && !jsonObj.get("RoomSkillParameters").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("RoomSkillParameters"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ResolveRoomResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ResolveRoomResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ResolveRoomResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ResolveRoomResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ResolveRoomResponse>() {
           @Override
           public void write(JsonWriter out, ResolveRoomResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ResolveRoomResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ResolveRoomResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ResolveRoomResponse
   * @throws IOException if the JSON string is invalid with respect to ResolveRoomResponse
   */
  public static ResolveRoomResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ResolveRoomResponse.class);
  }

  /**
   * Convert an instance of ResolveRoomResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

