/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.SendAnnouncementRequestContent;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * SendAnnouncementRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class SendAnnouncementRequest {
  public static final String SERIALIZED_NAME_ROOM_FILTERS = "RoomFilters";
  @SerializedName(SERIALIZED_NAME_ROOM_FILTERS)
  @javax.annotation.Nonnull
  private List roomFilters;

  public static final String SERIALIZED_NAME_CONTENT = "Content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  @javax.annotation.Nonnull
  private SendAnnouncementRequestContent content;

  public static final String SERIALIZED_NAME_TIME_TO_LIVE_IN_SECONDS = "TimeToLiveInSeconds";
  @SerializedName(SERIALIZED_NAME_TIME_TO_LIVE_IN_SECONDS)
  @javax.annotation.Nullable
  private Integer timeToLiveInSeconds;

  public static final String SERIALIZED_NAME_CLIENT_REQUEST_TOKEN = "ClientRequestToken";
  @SerializedName(SERIALIZED_NAME_CLIENT_REQUEST_TOKEN)
  @javax.annotation.Nonnull
  private String clientRequestToken;

  public SendAnnouncementRequest() {
  }

  public SendAnnouncementRequest roomFilters(@javax.annotation.Nonnull List roomFilters) {
    this.roomFilters = roomFilters;
    return this;
  }

  /**
   * Get roomFilters
   * @return roomFilters
   */
  @javax.annotation.Nonnull
  public List getRoomFilters() {
    return roomFilters;
  }

  public void setRoomFilters(@javax.annotation.Nonnull List roomFilters) {
    this.roomFilters = roomFilters;
  }


  public SendAnnouncementRequest content(@javax.annotation.Nonnull SendAnnouncementRequestContent content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nonnull
  public SendAnnouncementRequestContent getContent() {
    return content;
  }

  public void setContent(@javax.annotation.Nonnull SendAnnouncementRequestContent content) {
    this.content = content;
  }


  public SendAnnouncementRequest timeToLiveInSeconds(@javax.annotation.Nullable Integer timeToLiveInSeconds) {
    this.timeToLiveInSeconds = timeToLiveInSeconds;
    return this;
  }

  /**
   * Get timeToLiveInSeconds
   * @return timeToLiveInSeconds
   */
  @javax.annotation.Nullable
  public Integer getTimeToLiveInSeconds() {
    return timeToLiveInSeconds;
  }

  public void setTimeToLiveInSeconds(@javax.annotation.Nullable Integer timeToLiveInSeconds) {
    this.timeToLiveInSeconds = timeToLiveInSeconds;
  }


  public SendAnnouncementRequest clientRequestToken(@javax.annotation.Nonnull String clientRequestToken) {
    this.clientRequestToken = clientRequestToken;
    return this;
  }

  /**
   * Get clientRequestToken
   * @return clientRequestToken
   */
  @javax.annotation.Nonnull
  public String getClientRequestToken() {
    return clientRequestToken;
  }

  public void setClientRequestToken(@javax.annotation.Nonnull String clientRequestToken) {
    this.clientRequestToken = clientRequestToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendAnnouncementRequest sendAnnouncementRequest = (SendAnnouncementRequest) o;
    return Objects.equals(this.roomFilters, sendAnnouncementRequest.roomFilters) &&
        Objects.equals(this.content, sendAnnouncementRequest.content) &&
        Objects.equals(this.timeToLiveInSeconds, sendAnnouncementRequest.timeToLiveInSeconds) &&
        Objects.equals(this.clientRequestToken, sendAnnouncementRequest.clientRequestToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomFilters, content, timeToLiveInSeconds, clientRequestToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendAnnouncementRequest {\n");
    sb.append("    roomFilters: ").append(toIndentedString(roomFilters)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    timeToLiveInSeconds: ").append(toIndentedString(timeToLiveInSeconds)).append("\n");
    sb.append("    clientRequestToken: ").append(toIndentedString(clientRequestToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RoomFilters");
    openapiFields.add("Content");
    openapiFields.add("TimeToLiveInSeconds");
    openapiFields.add("ClientRequestToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("RoomFilters");
    openapiRequiredFields.add("Content");
    openapiRequiredFields.add("ClientRequestToken");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SendAnnouncementRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SendAnnouncementRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SendAnnouncementRequest is not found in the empty JSON string", SendAnnouncementRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SendAnnouncementRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SendAnnouncementRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SendAnnouncementRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `RoomFilters`
      List.validateJsonElement(jsonObj.get("RoomFilters"));
      // validate the required field `Content`
      SendAnnouncementRequestContent.validateJsonElement(jsonObj.get("Content"));
      // validate the optional field `TimeToLiveInSeconds`
      if (jsonObj.get("TimeToLiveInSeconds") != null && !jsonObj.get("TimeToLiveInSeconds").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("TimeToLiveInSeconds"));
      }
      // validate the required field `ClientRequestToken`
      String.validateJsonElement(jsonObj.get("ClientRequestToken"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SendAnnouncementRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SendAnnouncementRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SendAnnouncementRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SendAnnouncementRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<SendAnnouncementRequest>() {
           @Override
           public void write(JsonWriter out, SendAnnouncementRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SendAnnouncementRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SendAnnouncementRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SendAnnouncementRequest
   * @throws IOException if the JSON string is invalid with respect to SendAnnouncementRequest
   */
  public static SendAnnouncementRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SendAnnouncementRequest.class);
  }

  /**
   * Convert an instance of SendAnnouncementRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

