/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UpdateMeetingRoomConfigurationEndOfMeetingReminder;
import org.openapitools.client.model.UpdateMeetingRoomConfigurationInstantBooking;
import org.openapitools.client.model.UpdateMeetingRoomConfigurationRequireCheckIn;
import org.openapitools.client.model.UpdateProactiveJoin;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateProfileRequestMeetingRoomConfiguration
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class UpdateProfileRequestMeetingRoomConfiguration {
  public static final String SERIALIZED_NAME_ROOM_UTILIZATION_METRICS_ENABLED = "RoomUtilizationMetricsEnabled";
  @SerializedName(SERIALIZED_NAME_ROOM_UTILIZATION_METRICS_ENABLED)
  @javax.annotation.Nullable
  private Boolean roomUtilizationMetricsEnabled;

  public static final String SERIALIZED_NAME_END_OF_MEETING_REMINDER = "EndOfMeetingReminder";
  @SerializedName(SERIALIZED_NAME_END_OF_MEETING_REMINDER)
  @javax.annotation.Nullable
  private UpdateMeetingRoomConfigurationEndOfMeetingReminder endOfMeetingReminder;

  public static final String SERIALIZED_NAME_INSTANT_BOOKING = "InstantBooking";
  @SerializedName(SERIALIZED_NAME_INSTANT_BOOKING)
  @javax.annotation.Nullable
  private UpdateMeetingRoomConfigurationInstantBooking instantBooking;

  public static final String SERIALIZED_NAME_REQUIRE_CHECK_IN = "RequireCheckIn";
  @SerializedName(SERIALIZED_NAME_REQUIRE_CHECK_IN)
  @javax.annotation.Nullable
  private UpdateMeetingRoomConfigurationRequireCheckIn requireCheckIn;

  public static final String SERIALIZED_NAME_PROACTIVE_JOIN = "ProactiveJoin";
  @SerializedName(SERIALIZED_NAME_PROACTIVE_JOIN)
  @javax.annotation.Nullable
  private UpdateProactiveJoin proactiveJoin;

  public UpdateProfileRequestMeetingRoomConfiguration() {
  }

  public UpdateProfileRequestMeetingRoomConfiguration roomUtilizationMetricsEnabled(@javax.annotation.Nullable Boolean roomUtilizationMetricsEnabled) {
    this.roomUtilizationMetricsEnabled = roomUtilizationMetricsEnabled;
    return this;
  }

  /**
   * Get roomUtilizationMetricsEnabled
   * @return roomUtilizationMetricsEnabled
   */
  @javax.annotation.Nullable
  public Boolean getRoomUtilizationMetricsEnabled() {
    return roomUtilizationMetricsEnabled;
  }

  public void setRoomUtilizationMetricsEnabled(@javax.annotation.Nullable Boolean roomUtilizationMetricsEnabled) {
    this.roomUtilizationMetricsEnabled = roomUtilizationMetricsEnabled;
  }


  public UpdateProfileRequestMeetingRoomConfiguration endOfMeetingReminder(@javax.annotation.Nullable UpdateMeetingRoomConfigurationEndOfMeetingReminder endOfMeetingReminder) {
    this.endOfMeetingReminder = endOfMeetingReminder;
    return this;
  }

  /**
   * Get endOfMeetingReminder
   * @return endOfMeetingReminder
   */
  @javax.annotation.Nullable
  public UpdateMeetingRoomConfigurationEndOfMeetingReminder getEndOfMeetingReminder() {
    return endOfMeetingReminder;
  }

  public void setEndOfMeetingReminder(@javax.annotation.Nullable UpdateMeetingRoomConfigurationEndOfMeetingReminder endOfMeetingReminder) {
    this.endOfMeetingReminder = endOfMeetingReminder;
  }


  public UpdateProfileRequestMeetingRoomConfiguration instantBooking(@javax.annotation.Nullable UpdateMeetingRoomConfigurationInstantBooking instantBooking) {
    this.instantBooking = instantBooking;
    return this;
  }

  /**
   * Get instantBooking
   * @return instantBooking
   */
  @javax.annotation.Nullable
  public UpdateMeetingRoomConfigurationInstantBooking getInstantBooking() {
    return instantBooking;
  }

  public void setInstantBooking(@javax.annotation.Nullable UpdateMeetingRoomConfigurationInstantBooking instantBooking) {
    this.instantBooking = instantBooking;
  }


  public UpdateProfileRequestMeetingRoomConfiguration requireCheckIn(@javax.annotation.Nullable UpdateMeetingRoomConfigurationRequireCheckIn requireCheckIn) {
    this.requireCheckIn = requireCheckIn;
    return this;
  }

  /**
   * Get requireCheckIn
   * @return requireCheckIn
   */
  @javax.annotation.Nullable
  public UpdateMeetingRoomConfigurationRequireCheckIn getRequireCheckIn() {
    return requireCheckIn;
  }

  public void setRequireCheckIn(@javax.annotation.Nullable UpdateMeetingRoomConfigurationRequireCheckIn requireCheckIn) {
    this.requireCheckIn = requireCheckIn;
  }


  public UpdateProfileRequestMeetingRoomConfiguration proactiveJoin(@javax.annotation.Nullable UpdateProactiveJoin proactiveJoin) {
    this.proactiveJoin = proactiveJoin;
    return this;
  }

  /**
   * Get proactiveJoin
   * @return proactiveJoin
   */
  @javax.annotation.Nullable
  public UpdateProactiveJoin getProactiveJoin() {
    return proactiveJoin;
  }

  public void setProactiveJoin(@javax.annotation.Nullable UpdateProactiveJoin proactiveJoin) {
    this.proactiveJoin = proactiveJoin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProfileRequestMeetingRoomConfiguration updateProfileRequestMeetingRoomConfiguration = (UpdateProfileRequestMeetingRoomConfiguration) o;
    return Objects.equals(this.roomUtilizationMetricsEnabled, updateProfileRequestMeetingRoomConfiguration.roomUtilizationMetricsEnabled) &&
        Objects.equals(this.endOfMeetingReminder, updateProfileRequestMeetingRoomConfiguration.endOfMeetingReminder) &&
        Objects.equals(this.instantBooking, updateProfileRequestMeetingRoomConfiguration.instantBooking) &&
        Objects.equals(this.requireCheckIn, updateProfileRequestMeetingRoomConfiguration.requireCheckIn) &&
        Objects.equals(this.proactiveJoin, updateProfileRequestMeetingRoomConfiguration.proactiveJoin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roomUtilizationMetricsEnabled, endOfMeetingReminder, instantBooking, requireCheckIn, proactiveJoin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProfileRequestMeetingRoomConfiguration {\n");
    sb.append("    roomUtilizationMetricsEnabled: ").append(toIndentedString(roomUtilizationMetricsEnabled)).append("\n");
    sb.append("    endOfMeetingReminder: ").append(toIndentedString(endOfMeetingReminder)).append("\n");
    sb.append("    instantBooking: ").append(toIndentedString(instantBooking)).append("\n");
    sb.append("    requireCheckIn: ").append(toIndentedString(requireCheckIn)).append("\n");
    sb.append("    proactiveJoin: ").append(toIndentedString(proactiveJoin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RoomUtilizationMetricsEnabled");
    openapiFields.add("EndOfMeetingReminder");
    openapiFields.add("InstantBooking");
    openapiFields.add("RequireCheckIn");
    openapiFields.add("ProactiveJoin");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateProfileRequestMeetingRoomConfiguration
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateProfileRequestMeetingRoomConfiguration.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateProfileRequestMeetingRoomConfiguration is not found in the empty JSON string", UpdateProfileRequestMeetingRoomConfiguration.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateProfileRequestMeetingRoomConfiguration.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateProfileRequestMeetingRoomConfiguration` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `RoomUtilizationMetricsEnabled`
      if (jsonObj.get("RoomUtilizationMetricsEnabled") != null && !jsonObj.get("RoomUtilizationMetricsEnabled").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("RoomUtilizationMetricsEnabled"));
      }
      // validate the optional field `EndOfMeetingReminder`
      if (jsonObj.get("EndOfMeetingReminder") != null && !jsonObj.get("EndOfMeetingReminder").isJsonNull()) {
        UpdateMeetingRoomConfigurationEndOfMeetingReminder.validateJsonElement(jsonObj.get("EndOfMeetingReminder"));
      }
      // validate the optional field `InstantBooking`
      if (jsonObj.get("InstantBooking") != null && !jsonObj.get("InstantBooking").isJsonNull()) {
        UpdateMeetingRoomConfigurationInstantBooking.validateJsonElement(jsonObj.get("InstantBooking"));
      }
      // validate the optional field `RequireCheckIn`
      if (jsonObj.get("RequireCheckIn") != null && !jsonObj.get("RequireCheckIn").isJsonNull()) {
        UpdateMeetingRoomConfigurationRequireCheckIn.validateJsonElement(jsonObj.get("RequireCheckIn"));
      }
      // validate the optional field `ProactiveJoin`
      if (jsonObj.get("ProactiveJoin") != null && !jsonObj.get("ProactiveJoin").isJsonNull()) {
        UpdateProactiveJoin.validateJsonElement(jsonObj.get("ProactiveJoin"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateProfileRequestMeetingRoomConfiguration.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateProfileRequestMeetingRoomConfiguration' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateProfileRequestMeetingRoomConfiguration> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateProfileRequestMeetingRoomConfiguration.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateProfileRequestMeetingRoomConfiguration>() {
           @Override
           public void write(JsonWriter out, UpdateProfileRequestMeetingRoomConfiguration value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateProfileRequestMeetingRoomConfiguration read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateProfileRequestMeetingRoomConfiguration given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateProfileRequestMeetingRoomConfiguration
   * @throws IOException if the JSON string is invalid with respect to UpdateProfileRequestMeetingRoomConfiguration
   */
  public static UpdateProfileRequestMeetingRoomConfiguration fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateProfileRequestMeetingRoomConfiguration.class);
  }

  /**
   * Convert an instance of UpdateProfileRequestMeetingRoomConfiguration to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

