/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.EndOfMeetingReminderType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateMeetingRoomConfigurationEndOfMeetingReminder
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class UpdateMeetingRoomConfigurationEndOfMeetingReminder {
  public static final String SERIALIZED_NAME_REMINDER_AT_MINUTES = "ReminderAtMinutes";
  @SerializedName(SERIALIZED_NAME_REMINDER_AT_MINUTES)
  @javax.annotation.Nullable
  private List reminderAtMinutes;

  public static final String SERIALIZED_NAME_REMINDER_TYPE = "ReminderType";
  @SerializedName(SERIALIZED_NAME_REMINDER_TYPE)
  @javax.annotation.Nullable
  private EndOfMeetingReminderType reminderType;

  public static final String SERIALIZED_NAME_ENABLED = "Enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  @javax.annotation.Nullable
  private Boolean enabled;

  public UpdateMeetingRoomConfigurationEndOfMeetingReminder() {
  }

  public UpdateMeetingRoomConfigurationEndOfMeetingReminder reminderAtMinutes(@javax.annotation.Nullable List reminderAtMinutes) {
    this.reminderAtMinutes = reminderAtMinutes;
    return this;
  }

  /**
   * Get reminderAtMinutes
   * @return reminderAtMinutes
   */
  @javax.annotation.Nullable
  public List getReminderAtMinutes() {
    return reminderAtMinutes;
  }

  public void setReminderAtMinutes(@javax.annotation.Nullable List reminderAtMinutes) {
    this.reminderAtMinutes = reminderAtMinutes;
  }


  public UpdateMeetingRoomConfigurationEndOfMeetingReminder reminderType(@javax.annotation.Nullable EndOfMeetingReminderType reminderType) {
    this.reminderType = reminderType;
    return this;
  }

  /**
   * Get reminderType
   * @return reminderType
   */
  @javax.annotation.Nullable
  public EndOfMeetingReminderType getReminderType() {
    return reminderType;
  }

  public void setReminderType(@javax.annotation.Nullable EndOfMeetingReminderType reminderType) {
    this.reminderType = reminderType;
  }


  public UpdateMeetingRoomConfigurationEndOfMeetingReminder enabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @javax.annotation.Nullable
  public Boolean getEnabled() {
    return enabled;
  }

  public void setEnabled(@javax.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateMeetingRoomConfigurationEndOfMeetingReminder updateMeetingRoomConfigurationEndOfMeetingReminder = (UpdateMeetingRoomConfigurationEndOfMeetingReminder) o;
    return Objects.equals(this.reminderAtMinutes, updateMeetingRoomConfigurationEndOfMeetingReminder.reminderAtMinutes) &&
        Objects.equals(this.reminderType, updateMeetingRoomConfigurationEndOfMeetingReminder.reminderType) &&
        Objects.equals(this.enabled, updateMeetingRoomConfigurationEndOfMeetingReminder.enabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reminderAtMinutes, reminderType, enabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateMeetingRoomConfigurationEndOfMeetingReminder {\n");
    sb.append("    reminderAtMinutes: ").append(toIndentedString(reminderAtMinutes)).append("\n");
    sb.append("    reminderType: ").append(toIndentedString(reminderType)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ReminderAtMinutes");
    openapiFields.add("ReminderType");
    openapiFields.add("Enabled");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateMeetingRoomConfigurationEndOfMeetingReminder
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateMeetingRoomConfigurationEndOfMeetingReminder.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateMeetingRoomConfigurationEndOfMeetingReminder is not found in the empty JSON string", UpdateMeetingRoomConfigurationEndOfMeetingReminder.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateMeetingRoomConfigurationEndOfMeetingReminder.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateMeetingRoomConfigurationEndOfMeetingReminder` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ReminderAtMinutes`
      if (jsonObj.get("ReminderAtMinutes") != null && !jsonObj.get("ReminderAtMinutes").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("ReminderAtMinutes"));
      }
      // validate the optional field `ReminderType`
      if (jsonObj.get("ReminderType") != null && !jsonObj.get("ReminderType").isJsonNull()) {
        EndOfMeetingReminderType.validateJsonElement(jsonObj.get("ReminderType"));
      }
      // validate the optional field `Enabled`
      if (jsonObj.get("Enabled") != null && !jsonObj.get("Enabled").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("Enabled"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateMeetingRoomConfigurationEndOfMeetingReminder.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateMeetingRoomConfigurationEndOfMeetingReminder' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateMeetingRoomConfigurationEndOfMeetingReminder> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateMeetingRoomConfigurationEndOfMeetingReminder.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateMeetingRoomConfigurationEndOfMeetingReminder>() {
           @Override
           public void write(JsonWriter out, UpdateMeetingRoomConfigurationEndOfMeetingReminder value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateMeetingRoomConfigurationEndOfMeetingReminder read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateMeetingRoomConfigurationEndOfMeetingReminder given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateMeetingRoomConfigurationEndOfMeetingReminder
   * @throws IOException if the JSON string is invalid with respect to UpdateMeetingRoomConfigurationEndOfMeetingReminder
   */
  public static UpdateMeetingRoomConfigurationEndOfMeetingReminder fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateMeetingRoomConfigurationEndOfMeetingReminder.class);
  }

  /**
   * Convert an instance of UpdateMeetingRoomConfigurationEndOfMeetingReminder to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

