/*
 * Alexa For Business
 * Alexa for Business has been retired and is no longer supported.
 *
 * The version of the OpenAPI document: 2017-11-09
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.DistanceUnit;
import org.openapitools.client.model.TemperatureUnit;
import org.openapitools.client.model.UpdateProfileRequestMeetingRoomConfiguration;
import org.openapitools.client.model.WakeWord;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateProfileRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:07:53.324908+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class UpdateProfileRequest {
  public static final String SERIALIZED_NAME_PROFILE_ARN = "ProfileArn";
  @SerializedName(SERIALIZED_NAME_PROFILE_ARN)
  @javax.annotation.Nullable
  private String profileArn;

  public static final String SERIALIZED_NAME_PROFILE_NAME = "ProfileName";
  @SerializedName(SERIALIZED_NAME_PROFILE_NAME)
  @javax.annotation.Nullable
  private String profileName;

  public static final String SERIALIZED_NAME_IS_DEFAULT = "IsDefault";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT)
  @javax.annotation.Nullable
  private Boolean isDefault;

  public static final String SERIALIZED_NAME_TIMEZONE = "Timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nullable
  private String timezone;

  public static final String SERIALIZED_NAME_ADDRESS = "Address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  @javax.annotation.Nullable
  private String address;

  public static final String SERIALIZED_NAME_DISTANCE_UNIT = "DistanceUnit";
  @SerializedName(SERIALIZED_NAME_DISTANCE_UNIT)
  @javax.annotation.Nullable
  private DistanceUnit distanceUnit;

  public static final String SERIALIZED_NAME_TEMPERATURE_UNIT = "TemperatureUnit";
  @SerializedName(SERIALIZED_NAME_TEMPERATURE_UNIT)
  @javax.annotation.Nullable
  private TemperatureUnit temperatureUnit;

  public static final String SERIALIZED_NAME_WAKE_WORD = "WakeWord";
  @SerializedName(SERIALIZED_NAME_WAKE_WORD)
  @javax.annotation.Nullable
  private WakeWord wakeWord;

  public static final String SERIALIZED_NAME_LOCALE = "Locale";
  @SerializedName(SERIALIZED_NAME_LOCALE)
  @javax.annotation.Nullable
  private String locale;

  public static final String SERIALIZED_NAME_SETUP_MODE_DISABLED = "SetupModeDisabled";
  @SerializedName(SERIALIZED_NAME_SETUP_MODE_DISABLED)
  @javax.annotation.Nullable
  private Boolean setupModeDisabled;

  public static final String SERIALIZED_NAME_MAX_VOLUME_LIMIT = "MaxVolumeLimit";
  @SerializedName(SERIALIZED_NAME_MAX_VOLUME_LIMIT)
  @javax.annotation.Nullable
  private Integer maxVolumeLimit;

  public static final String SERIALIZED_NAME_PS_T_N_ENABLED = "PSTNEnabled";
  @SerializedName(SERIALIZED_NAME_PS_T_N_ENABLED)
  @javax.annotation.Nullable
  private Boolean psTNEnabled;

  public static final String SERIALIZED_NAME_DATA_RETENTION_OPT_IN = "DataRetentionOptIn";
  @SerializedName(SERIALIZED_NAME_DATA_RETENTION_OPT_IN)
  @javax.annotation.Nullable
  private Boolean dataRetentionOptIn;

  public static final String SERIALIZED_NAME_MEETING_ROOM_CONFIGURATION = "MeetingRoomConfiguration";
  @SerializedName(SERIALIZED_NAME_MEETING_ROOM_CONFIGURATION)
  @javax.annotation.Nullable
  private UpdateProfileRequestMeetingRoomConfiguration meetingRoomConfiguration;

  public UpdateProfileRequest() {
  }

  public UpdateProfileRequest profileArn(@javax.annotation.Nullable String profileArn) {
    this.profileArn = profileArn;
    return this;
  }

  /**
   * Get profileArn
   * @return profileArn
   */
  @javax.annotation.Nullable
  public String getProfileArn() {
    return profileArn;
  }

  public void setProfileArn(@javax.annotation.Nullable String profileArn) {
    this.profileArn = profileArn;
  }


  public UpdateProfileRequest profileName(@javax.annotation.Nullable String profileName) {
    this.profileName = profileName;
    return this;
  }

  /**
   * Get profileName
   * @return profileName
   */
  @javax.annotation.Nullable
  public String getProfileName() {
    return profileName;
  }

  public void setProfileName(@javax.annotation.Nullable String profileName) {
    this.profileName = profileName;
  }


  public UpdateProfileRequest isDefault(@javax.annotation.Nullable Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

  /**
   * Get isDefault
   * @return isDefault
   */
  @javax.annotation.Nullable
  public Boolean getIsDefault() {
    return isDefault;
  }

  public void setIsDefault(@javax.annotation.Nullable Boolean isDefault) {
    this.isDefault = isDefault;
  }


  public UpdateProfileRequest timezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }


  public UpdateProfileRequest address(@javax.annotation.Nullable String address) {
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  public String getAddress() {
    return address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }


  public UpdateProfileRequest distanceUnit(@javax.annotation.Nullable DistanceUnit distanceUnit) {
    this.distanceUnit = distanceUnit;
    return this;
  }

  /**
   * Get distanceUnit
   * @return distanceUnit
   */
  @javax.annotation.Nullable
  public DistanceUnit getDistanceUnit() {
    return distanceUnit;
  }

  public void setDistanceUnit(@javax.annotation.Nullable DistanceUnit distanceUnit) {
    this.distanceUnit = distanceUnit;
  }


  public UpdateProfileRequest temperatureUnit(@javax.annotation.Nullable TemperatureUnit temperatureUnit) {
    this.temperatureUnit = temperatureUnit;
    return this;
  }

  /**
   * Get temperatureUnit
   * @return temperatureUnit
   */
  @javax.annotation.Nullable
  public TemperatureUnit getTemperatureUnit() {
    return temperatureUnit;
  }

  public void setTemperatureUnit(@javax.annotation.Nullable TemperatureUnit temperatureUnit) {
    this.temperatureUnit = temperatureUnit;
  }


  public UpdateProfileRequest wakeWord(@javax.annotation.Nullable WakeWord wakeWord) {
    this.wakeWord = wakeWord;
    return this;
  }

  /**
   * Get wakeWord
   * @return wakeWord
   */
  @javax.annotation.Nullable
  public WakeWord getWakeWord() {
    return wakeWord;
  }

  public void setWakeWord(@javax.annotation.Nullable WakeWord wakeWord) {
    this.wakeWord = wakeWord;
  }


  public UpdateProfileRequest locale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * Get locale
   * @return locale
   */
  @javax.annotation.Nullable
  public String getLocale() {
    return locale;
  }

  public void setLocale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
  }


  public UpdateProfileRequest setupModeDisabled(@javax.annotation.Nullable Boolean setupModeDisabled) {
    this.setupModeDisabled = setupModeDisabled;
    return this;
  }

  /**
   * Get setupModeDisabled
   * @return setupModeDisabled
   */
  @javax.annotation.Nullable
  public Boolean getSetupModeDisabled() {
    return setupModeDisabled;
  }

  public void setSetupModeDisabled(@javax.annotation.Nullable Boolean setupModeDisabled) {
    this.setupModeDisabled = setupModeDisabled;
  }


  public UpdateProfileRequest maxVolumeLimit(@javax.annotation.Nullable Integer maxVolumeLimit) {
    this.maxVolumeLimit = maxVolumeLimit;
    return this;
  }

  /**
   * Get maxVolumeLimit
   * @return maxVolumeLimit
   */
  @javax.annotation.Nullable
  public Integer getMaxVolumeLimit() {
    return maxVolumeLimit;
  }

  public void setMaxVolumeLimit(@javax.annotation.Nullable Integer maxVolumeLimit) {
    this.maxVolumeLimit = maxVolumeLimit;
  }


  public UpdateProfileRequest psTNEnabled(@javax.annotation.Nullable Boolean psTNEnabled) {
    this.psTNEnabled = psTNEnabled;
    return this;
  }

  /**
   * Get psTNEnabled
   * @return psTNEnabled
   */
  @javax.annotation.Nullable
  public Boolean getPsTNEnabled() {
    return psTNEnabled;
  }

  public void setPsTNEnabled(@javax.annotation.Nullable Boolean psTNEnabled) {
    this.psTNEnabled = psTNEnabled;
  }


  public UpdateProfileRequest dataRetentionOptIn(@javax.annotation.Nullable Boolean dataRetentionOptIn) {
    this.dataRetentionOptIn = dataRetentionOptIn;
    return this;
  }

  /**
   * Get dataRetentionOptIn
   * @return dataRetentionOptIn
   */
  @javax.annotation.Nullable
  public Boolean getDataRetentionOptIn() {
    return dataRetentionOptIn;
  }

  public void setDataRetentionOptIn(@javax.annotation.Nullable Boolean dataRetentionOptIn) {
    this.dataRetentionOptIn = dataRetentionOptIn;
  }


  public UpdateProfileRequest meetingRoomConfiguration(@javax.annotation.Nullable UpdateProfileRequestMeetingRoomConfiguration meetingRoomConfiguration) {
    this.meetingRoomConfiguration = meetingRoomConfiguration;
    return this;
  }

  /**
   * Get meetingRoomConfiguration
   * @return meetingRoomConfiguration
   */
  @javax.annotation.Nullable
  public UpdateProfileRequestMeetingRoomConfiguration getMeetingRoomConfiguration() {
    return meetingRoomConfiguration;
  }

  public void setMeetingRoomConfiguration(@javax.annotation.Nullable UpdateProfileRequestMeetingRoomConfiguration meetingRoomConfiguration) {
    this.meetingRoomConfiguration = meetingRoomConfiguration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateProfileRequest updateProfileRequest = (UpdateProfileRequest) o;
    return Objects.equals(this.profileArn, updateProfileRequest.profileArn) &&
        Objects.equals(this.profileName, updateProfileRequest.profileName) &&
        Objects.equals(this.isDefault, updateProfileRequest.isDefault) &&
        Objects.equals(this.timezone, updateProfileRequest.timezone) &&
        Objects.equals(this.address, updateProfileRequest.address) &&
        Objects.equals(this.distanceUnit, updateProfileRequest.distanceUnit) &&
        Objects.equals(this.temperatureUnit, updateProfileRequest.temperatureUnit) &&
        Objects.equals(this.wakeWord, updateProfileRequest.wakeWord) &&
        Objects.equals(this.locale, updateProfileRequest.locale) &&
        Objects.equals(this.setupModeDisabled, updateProfileRequest.setupModeDisabled) &&
        Objects.equals(this.maxVolumeLimit, updateProfileRequest.maxVolumeLimit) &&
        Objects.equals(this.psTNEnabled, updateProfileRequest.psTNEnabled) &&
        Objects.equals(this.dataRetentionOptIn, updateProfileRequest.dataRetentionOptIn) &&
        Objects.equals(this.meetingRoomConfiguration, updateProfileRequest.meetingRoomConfiguration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileArn, profileName, isDefault, timezone, address, distanceUnit, temperatureUnit, wakeWord, locale, setupModeDisabled, maxVolumeLimit, psTNEnabled, dataRetentionOptIn, meetingRoomConfiguration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateProfileRequest {\n");
    sb.append("    profileArn: ").append(toIndentedString(profileArn)).append("\n");
    sb.append("    profileName: ").append(toIndentedString(profileName)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    distanceUnit: ").append(toIndentedString(distanceUnit)).append("\n");
    sb.append("    temperatureUnit: ").append(toIndentedString(temperatureUnit)).append("\n");
    sb.append("    wakeWord: ").append(toIndentedString(wakeWord)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    setupModeDisabled: ").append(toIndentedString(setupModeDisabled)).append("\n");
    sb.append("    maxVolumeLimit: ").append(toIndentedString(maxVolumeLimit)).append("\n");
    sb.append("    psTNEnabled: ").append(toIndentedString(psTNEnabled)).append("\n");
    sb.append("    dataRetentionOptIn: ").append(toIndentedString(dataRetentionOptIn)).append("\n");
    sb.append("    meetingRoomConfiguration: ").append(toIndentedString(meetingRoomConfiguration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ProfileArn");
    openapiFields.add("ProfileName");
    openapiFields.add("IsDefault");
    openapiFields.add("Timezone");
    openapiFields.add("Address");
    openapiFields.add("DistanceUnit");
    openapiFields.add("TemperatureUnit");
    openapiFields.add("WakeWord");
    openapiFields.add("Locale");
    openapiFields.add("SetupModeDisabled");
    openapiFields.add("MaxVolumeLimit");
    openapiFields.add("PSTNEnabled");
    openapiFields.add("DataRetentionOptIn");
    openapiFields.add("MeetingRoomConfiguration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateProfileRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateProfileRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateProfileRequest is not found in the empty JSON string", UpdateProfileRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateProfileRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateProfileRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `ProfileArn`
      if (jsonObj.get("ProfileArn") != null && !jsonObj.get("ProfileArn").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ProfileArn"));
      }
      // validate the optional field `ProfileName`
      if (jsonObj.get("ProfileName") != null && !jsonObj.get("ProfileName").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("ProfileName"));
      }
      // validate the optional field `IsDefault`
      if (jsonObj.get("IsDefault") != null && !jsonObj.get("IsDefault").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("IsDefault"));
      }
      // validate the optional field `Timezone`
      if (jsonObj.get("Timezone") != null && !jsonObj.get("Timezone").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Timezone"));
      }
      // validate the optional field `Address`
      if (jsonObj.get("Address") != null && !jsonObj.get("Address").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Address"));
      }
      // validate the optional field `DistanceUnit`
      if (jsonObj.get("DistanceUnit") != null && !jsonObj.get("DistanceUnit").isJsonNull()) {
        DistanceUnit.validateJsonElement(jsonObj.get("DistanceUnit"));
      }
      // validate the optional field `TemperatureUnit`
      if (jsonObj.get("TemperatureUnit") != null && !jsonObj.get("TemperatureUnit").isJsonNull()) {
        TemperatureUnit.validateJsonElement(jsonObj.get("TemperatureUnit"));
      }
      // validate the optional field `WakeWord`
      if (jsonObj.get("WakeWord") != null && !jsonObj.get("WakeWord").isJsonNull()) {
        WakeWord.validateJsonElement(jsonObj.get("WakeWord"));
      }
      // validate the optional field `Locale`
      if (jsonObj.get("Locale") != null && !jsonObj.get("Locale").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("Locale"));
      }
      // validate the optional field `SetupModeDisabled`
      if (jsonObj.get("SetupModeDisabled") != null && !jsonObj.get("SetupModeDisabled").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("SetupModeDisabled"));
      }
      // validate the optional field `MaxVolumeLimit`
      if (jsonObj.get("MaxVolumeLimit") != null && !jsonObj.get("MaxVolumeLimit").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("MaxVolumeLimit"));
      }
      // validate the optional field `PSTNEnabled`
      if (jsonObj.get("PSTNEnabled") != null && !jsonObj.get("PSTNEnabled").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("PSTNEnabled"));
      }
      // validate the optional field `DataRetentionOptIn`
      if (jsonObj.get("DataRetentionOptIn") != null && !jsonObj.get("DataRetentionOptIn").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("DataRetentionOptIn"));
      }
      // validate the optional field `MeetingRoomConfiguration`
      if (jsonObj.get("MeetingRoomConfiguration") != null && !jsonObj.get("MeetingRoomConfiguration").isJsonNull()) {
        UpdateProfileRequestMeetingRoomConfiguration.validateJsonElement(jsonObj.get("MeetingRoomConfiguration"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateProfileRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateProfileRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateProfileRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateProfileRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateProfileRequest>() {
           @Override
           public void write(JsonWriter out, UpdateProfileRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateProfileRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateProfileRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateProfileRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateProfileRequest
   */
  public static UpdateProfileRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateProfileRequest.class);
  }

  /**
   * Convert an instance of UpdateProfileRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

